export type RoleImportance = "core" | "key" | "important" | "support";
export type RolePhase = "with-ball" | "without-ball";

export type RoleDefinition = {
  id: string;
  name: string;
  positionGroup: string;
  phase: RolePhase;
  coreAttributes?: string[];
  keyAttributes: string[];
  importantAttributes: string[];
  supportAttributes?: string[];
};

export const ROLE_DEFINITIONS: RoleDefinition[] = [
{
  id: "poacher",
  name: "Lis pola karnego",
  positionGroup: "Napastnik",
  phase: "with-ball",
  coreAttributes: [
    "Wykańczanie akcji",
    "Przewidywanie",
    "Koncentracja",
  ],
  keyAttributes: [
    "Gra głową",
    "Gra bez piłki",
    "Opanowanie",
    "Przyspieszenie",
  ],
  importantAttributes: [
    "Równowaga",
  ],
  supportAttributes: [
    "Decyzje",
    "Przyjęcie piłki",
    "Technika",
  ],
},
{
  id: "deep-lying-forward",
  name: "Cofnięty napastnik",
  positionGroup: "Napastnik",
  phase: "with-ball",
  coreAttributes: [
    "Wykańczanie akcji",
  ],
  keyAttributes: [
    "Przyjęcie piłki",
    "Technika",
    "Gra bez piłki",
    "Opanowanie",
    "Siła",
  ],
  importantAttributes: [
    "Drybling",
    "Podania",
    "Przewidywanie",
    "Współpraca",
    "Równowaga",
  ],
  supportAttributes: [
    "Decyzje",
    "Przegląd sytuacji",
  ],
},
{
  id: "target-forward",
  name: "Odgrywający",
  positionGroup: "Napastnik",
  phase: "with-ball",
  coreAttributes: [
    "Wykańczanie akcji",
    "Skoczność",
    "Siła",
    "Równowaga",
  ],
  keyAttributes: [
    "Gra głową",
    "Agresja",
    "Gra bez piłki",
    "Opanowanie",
    "Waleczność",
  ],
  importantAttributes: [
    "Przewidywanie",
    "Współpraca",
  ],
  supportAttributes: [
    "Przyjęcie piłki",
    "Decyzje",
  ],
},
{
  id: "complete-forward",
  name: "Środkowy napastnik",
  positionGroup: "Napastnik",
  phase: "with-ball",
  coreAttributes: [
    "Wykańczanie akcji",
  ],
  keyAttributes: [
    "Gra głową",
    "Przyjęcie piłki",
    "Technika",
    "Opanowanie",
    "Gra bez piłki",
    "Przyspieszenie",
    "Siła",
  ],
  importantAttributes: [
    "Drybling",
    "Podania",
    "Przewidywanie",
    "Zwinność",
    "Szybkość",
    "Skoczność",
    "Równowaga",
  ],
  supportAttributes: [
    "Decyzje",
  ],
},
{
  id: "advanced-forward",
  name: "Wychodzący napastnik",
  positionGroup: "Napastnik",
  phase: "with-ball",
  coreAttributes: [
    "Wykańczanie akcji",
    "Pracowitość",
    "Drybling",
  ],
  keyAttributes: [
    "Przyjęcie piłki",
    "Technika",
    "Opanowanie",
    "Gra bez piłki",
  ],
  importantAttributes: [
    "Podania",
    "Przewidywanie",
    "Zwinność",
    "Szybkość",
    "Równowaga",
  ],
  supportAttributes: [
    "Wytrzymałość",
    "Gra głową",
    "Dośrodkowania",
  ],
},
{
  id: "false-nine",
  name: "Fałszywa 9",
  positionGroup: "Napastnik",
  phase: "with-ball",
  coreAttributes: [
    "Podania",
    "Drybling",
    "Przyspieszenie",
    "Współpraca",
  ],
  keyAttributes: [
    "Przyjęcie piłki",
    "Technika",
    "Przegląd sytuacji",
    "Opanowanie",
    "Gra bez piłki",
    "Decyzje",
  ],
  importantAttributes: [
    "Zwinność",
    "Równowaga",
    "Błyskotliwość",
    "Wykańczanie akcji",
    "Przewidywanie",
  ],
  supportAttributes: [],
},
{
  id: "off-ball-complete-forward",
  name: "Środkowy napastnik",
  positionGroup: "Napastnik",
  phase: "without-ball",
  coreAttributes: [
    "Pracowitość",
    "Przewidywanie",
  ],
  keyAttributes: [
    "Decyzje",
  ],
  importantAttributes: [
    "Krycie",
    "Współpraca",
  ],
  supportAttributes: [
    "Agresja",
    "Gra bez piłki",
    "Wytrzymałość",
  ],
},
{
  id: "off-ball-hanging-receiving-forward",
  name: "Podwieszony przyjmujący środkowy napastnik",
  positionGroup: "Napastnik",
  phase: "without-ball",
  coreAttributes: [
    "Koncentracja",
    "Szybkość",
    "Przewidywanie",
    "Współpraca",
  ],
  keyAttributes: [
    "Decyzje",
    "Gra bez piłki",
  ],
  importantAttributes: [
    "Krycie",
  ],
  supportAttributes: [
    "Przyjęcie piłki",
    "Opanowanie",
    "Przyspieszenie",
  ],
},
{
  id: "off-ball-central-receiving-forward",
  name: "Centralny przyjmujący środkowy napastnik",
  positionGroup: "Napastnik",
  phase: "without-ball",
  coreAttributes: [
    "Koncentracja",
    "Przewidywanie",
    "Współpraca",
    "Równowaga",
  ],
  keyAttributes: [
    "Decyzje",
    "Gra bez piłki",
  ],
  importantAttributes: [
    "Krycie",
  ],
  supportAttributes: [
    "Przyjęcie piłki",
    "Opanowanie",
    "Siła",
  ],
},
{
  id: "off-ball-tracking-forward",
  name: "Śledzący środkowy napastnik",
  positionGroup: "Napastnik",
  phase: "without-ball",
  coreAttributes: [
    "Pracowitość",
    "Przewidywanie",
    "Współpraca",
  ],
  keyAttributes: [
    "Agresja",
    "Decyzje",
    "Wytrzymałość",
  ],
  importantAttributes: [
    "Ustawianie się",
  ],
  supportAttributes: [
    "Krycie",
    "Gra bez piłki",
  ],
},
{
  id: "winger-with-ball",
  name: "Skrzydłowy",
  positionGroup: "Skrzydłowy",
  phase: "with-ball",
  coreAttributes: [
    "Drybling",
    "Zwinność",
    "Szybkość",
    "Współpraca",
  ],
  keyAttributes: [
    "Dośrodkowania",
    "Technika",
    "Przyspieszenie",
  ],
  importantAttributes: [
    "Podania",
    "Błyskotliwość",
    "Pracowitość",
    "Przewidywanie",
    "Równowaga",
  ],
  supportAttributes: [
    "Przyjęcie piłki",
    "Gra bez piłki",
    "Wytrzymałość",
  ],
},
{
  id: "wide-forward-with-ball",
  name: "Boczny napastnik",
  positionGroup: "Skrzydłowy",
  phase: "with-ball",
  coreAttributes: [
    "Drybling",
    "Przewidywanie",
    "Zwinność",
    "Szybkość",
  ],
  keyAttributes: [
    "Przyjęcie piłki",
    "Technika",
    "Gra bez piłki",
    "Przyspieszenie",
  ],
  importantAttributes: [
    "Podania",
    "Wykańczanie akcji",
    "Pracowitość",
    "Równowaga",
    "Błyskotliwość",
  ],
  supportAttributes: [
    "Dośrodkowania",
    "Opanowanie",
    "Wytrzymałość",
  ],
},
{
  id: "inverted-winger-with-ball",
  name: "Odwrócony skrzydłowy",
  positionGroup: "Skrzydłowy",
  phase: "with-ball",
  coreAttributes: [
    "Drybling",
    "Współpraca",
    "Zwinność",
    "Przyspieszenie",
  ],
  keyAttributes: [
    "Przyjęcie piłki",
    "Technika",
    "Opanowanie",
  ],
  importantAttributes: [
    "Podania",
    "Strzały z dystansu",
    "Błyskotliwość",
    "Pracowitość",
    "Przewidywanie",
    "Szybkość",
    "Równowaga",
  ],
  supportAttributes: [
    "Dośrodkowania",
    "Gra bez piłki",
    "Przegląd sytuacji",
    "Wytrzymałość",
  ],
},
{
  id: "inside-forward-with-ball",
  name: "Schodzący napastnik",
  positionGroup: "Skrzydłowy",
  phase: "with-ball",
  coreAttributes: [
    "Drybling",
    "Przewidywanie",
    "Zwinność",
  ],
  keyAttributes: [
    "Przyjęcie piłki",
    "Technika",
    "Gra bez piłki",
    "Opanowanie",
    "Przyspieszenie",
  ],
  importantAttributes: [
    "Podania",
    "Strzały z dystansu",
    "Wykańczanie akcji",
    "Pracowitość",
    "Błyskotliwość",
    "Równowaga",
    "Szybkość",
  ],
  supportAttributes: [
    "Dośrodkowania",
    "Przegląd sytuacji",
    "Wytrzymałość",
  ],
},
{
  id: "wide-playmaker-with-ball",
  name: "Rozgrywający skrzydłowy",
  positionGroup: "Skrzydłowy",
  phase: "with-ball",
  coreAttributes: [
    "Drybling",
    "Podania",
    "Współpraca",
  ],
  keyAttributes: [
    "Dośrodkowania",
    "Przyjęcie piłki",
    "Technika",
    "Decyzje",
    "Gra bez piłki",
    "Opanowanie",
    "Przegląd sytuacji",
    "Przyspieszenie",
  ],
  importantAttributes: [
    "Szybkość",
    "Zwinność",
    "Pracowitość",
    "Przewidywanie",
    "Błyskotliwość",
  ],
  supportAttributes: [
    "Wytrzymałość",
  ],
},

{
  id: "winger-without-ball",
  name: "Skrzydłowy",
  positionGroup: "Skrzydłowy",
  phase: "without-ball",
  coreAttributes: [
    "Pracowitość",
    "Przewidywanie",
    "Współpraca",
    "Przyspieszenie",
  ],
  keyAttributes: [
    "Decyzje",
  ],
  importantAttributes: [
    "Szybkość",
    "Zwinność",
  ],
  supportAttributes: [
    "Krycie",
    "Agresja",
    "Gra bez piłki",
    "Wytrzymałość",
  ],
},
{
  id: "tracking-winger-without-ball",
  name: "Śledzący skrzydłowy",
  positionGroup: "Skrzydłowy",
  phase: "without-ball",
  coreAttributes: [
    "Pracowitość",
    "Przewidywanie",
    "Współpraca",
  ],
  keyAttributes: [
    "Agresja",
    "Decyzje",
    "Przyspieszenie",
    "Wytrzymałość",
  ],
  importantAttributes: [
    "Krycie",
    "Ustawianie się",
    "Zwinność",
    "Szybkość",
  ],
  supportAttributes: [
    "Odbiór piłki",
    "Gra bez piłki",
  ],
},
{
  id: "wide-receiving-winger-without-ball",
  name: "Boczny przyjmujący skrzydłowy",
  positionGroup: "Skrzydłowy",
  phase: "without-ball",
  coreAttributes: [
    "Koncentracja",
    "Przewidywanie",
    "Współpraca",
    "Szybkość",
  ],
  keyAttributes: [
    "Decyzje",
    "Gra bez piłki",
  ],
  importantAttributes: [
    "Krycie",
    "Drybling",
    "Zwinność",
  ],
  supportAttributes: [
    "Przyjęcie piłki",
    "Opanowanie",
    "Przyspieszenie",
  ],
},
{
  id: "inverted-receiving-winger-without-ball",
  name: "Odwrócony przyjmujący skrzydłowy",
  positionGroup: "Skrzydłowy",
  phase: "without-ball",
  coreAttributes: [
    "Koncentracja",
    "Przewidywanie",
    "Współpraca",
    "Równowaga",
  ],
  keyAttributes: [
    "Decyzje",
    "Gra bez piłki",
  ],
  importantAttributes: [
    "Drybling",
    "Krycie",
  ],
  supportAttributes: [
    "Przyjęcie piłki",
    "Opanowanie",
    "Przyspieszenie",
    "Siła",
  ],
},
{
  id: "wide-midfielder-winger-with-ball",
  name: "Skrzydłowy",
  positionGroup: "Boczny pomocnik",
  phase: "with-ball",
  coreAttributes: [
    "Drybling",
    "Szybkość",
    "Zwinność",
    "Współpraca",
  ],
  keyAttributes: [
    "Dośrodkowania",
    "Technika",
    "Przyspieszenie",
  ],
  importantAttributes: [
    "Podania",
    "Pracowitość",
    "Przewidywanie",
    "Błyskotliwość",
    "Równowaga",
  ],
  supportAttributes: [
    "Przyjęcie piłki",
    "Gra bez piłki",
    "Wytrzymałość",
  ],
},
{
  id: "wide-midfielder-inverted-winger-with-ball",
  name: "Odwrócony skrzydłowy",
  positionGroup: "Boczny pomocnik",
  phase: "with-ball",
  coreAttributes: [
    "Drybling",
    "Przyspieszenie",
    "Zwinność",
    "Współpraca",
  ],
  keyAttributes: [
    "Przyjęcie piłki",
    "Technika",
    "Opanowanie",
  ],
  importantAttributes: [
    "Błyskotliwość",
    "Pracowitość",
    "Przewidywanie",
    "Podania",
    "Strzały z dystansu",
    "Szybkość",
    "Równowaga",
  ],
  supportAttributes: [
    "Dośrodkowania",
    "Gra bez piłki",
    "Przegląd sytuacji",
    "Wytrzymałość",
  ],
},
{
  id: "wide-midfielder-wide-playmaker-with-ball",
  name: "Rozgrywający skrzydłowy",
  positionGroup: "Boczny pomocnik",
  phase: "with-ball",
  coreAttributes: [
    "Drybling",
    "Podania",
    "Współpraca",
  ],
  keyAttributes: [
    "Dośrodkowania",
    "Przyjęcie piłki",
    "Technika",
    "Decyzje",
    "Gra bez piłki",
    "Opanowanie",
    "Przegląd sytuacji",
    "Przyspieszenie",
  ],
  importantAttributes: [
    "Szybkość",
    "Zwinność",
    "Przewidywanie",
    "Pracowitość",
    "Błyskotliwość",
  ],
  supportAttributes: [
    "Wytrzymałość",
  ],
},
{
  id: "wide-midfielder-with-ball",
  name: "Boczny pomocnik",
  positionGroup: "Boczny pomocnik",
  phase: "with-ball",
  coreAttributes: [
    "Podania",
    "Pracowitość",
    "Szybkość",
    "Współpraca",
  ],
  keyAttributes: [
    "Dośrodkowania",
    "Technika",
    "Decyzje",
    "Wytrzymałość",
  ],
  importantAttributes: [
    "Drybling",
    "Przewidywanie",
    "Zwinność",
  ],
  supportAttributes: [
    "Przyjęcie piłki",
    "Gra bez piłki",
    "Opanowanie",
    "Przegląd sytuacji",
    "Przyspieszenie",
  ],
},

{
  id: "wide-midfielder-without-ball",
  name: "Boczny pomocnik",
  positionGroup: "Boczny pomocnik",
  phase: "without-ball",
  coreAttributes: [
    "Pracowitość",
    "Współpraca",
  ],
  keyAttributes: [
    "Decyzje",
    "Przyspieszenie",
  ],
  importantAttributes: [
    "Przewidywanie",
    "Krycie",
    "Szybkość",
    "Zwinność",
  ],
  supportAttributes: [
    "Agresja",
    "Gra bez piłki",
    "Wytrzymałość",
  ],
},
{
  id: "tracking-wide-midfielder-without-ball",
  name: "Śledzący boczny pomocnik",
  positionGroup: "Boczny pomocnik",
  phase: "without-ball",
  coreAttributes: [
    "Pracowitość",
    "Przewidywanie",
    "Współpraca",
    "Wytrzymałość",
  ],
  keyAttributes: [
    "Agresja",
    "Decyzje",
    "Przyspieszenie",
  ],
  importantAttributes: [
    "Szybkość",
    "Zwinność",
    "Krycie",
    "Ustawianie się",
  ],
  supportAttributes: [
    "Odbiór piłki",
    "Gra bez piłki",
  ],
},
{
  id: "wide-receiving-midfielder-without-ball",
  name: "Boczny przyjmujący pomocnik",
  positionGroup: "Boczny pomocnik",
  phase: "without-ball",
  coreAttributes: [
    "Koncentracja",
    "Przewidywanie",
    "Współpraca",
    "Szybkość",
  ],
  keyAttributes: [
    "Decyzje",
    "Gra bez piłki",
  ],
  importantAttributes: [
    "Krycie",
    "Drybling",
    "Zwinność",
  ],
  supportAttributes: [
    "Przyjęcie piłki",
    "Opanowanie",
    "Przyspieszenie",
  ],
},
{
  id: "complete-wing-back-with-ball",
  name: "Zaawansowany boczny wysunięty obrońca",
  positionGroup: "Wahadłowy",
  phase: "with-ball",
  coreAttributes: [
    "Drybling",
    "Szybkość",
    "Zwinność",
    "Pracowitość",
    "Współpraca",
  ],
  keyAttributes: [
    "Dośrodkowania",
    "Technika",
    "Gra bez piłki",
    "Przyspieszenie",
    "Wytrzymałość",
  ],
  importantAttributes: [
    "Krycie",
    "Podania",
    "Błyskotliwość",
    "Równowaga",
    "Ustawianie się",
    "Przewidywanie",
  ],
  supportAttributes: [
    "Odbiór piłki",
    "Przyjęcie piłki",
    "Decyzje",
  ],
},
{
  id: "wide-playmaker-wing-back-with-ball",
  name: "Rozgrywający wysunięty boczny obrońca",
  positionGroup: "Wahadłowy",
  phase: "with-ball",
  coreAttributes: [
    "Podania",
    "Współpraca",
  ],
  keyAttributes: [
    "Odbiór piłki",
    "Przyjęcie piłki",
    "Technika",
    "Decyzje",
    "Opanowanie",
    "Przegląd sytuacji",
    "Przyspieszenie",
  ],
  importantAttributes: [
    "Drybling",
    "Krycie",
    "Koncentracja",
    "Pracowitość",
    "Przewidywanie",
    "Ustawianie się",
    "Zwinność",
    "Szybkość",
  ],
  supportAttributes: [
    "Dośrodkowania",
    "Gra bez piłki",
    "Wytrzymałość",
  ],
},
{
  id: "wing-back-with-ball",
  name: "Wysunięty boczny obrońca",
  positionGroup: "Wahadłowy",
  phase: "with-ball",
  coreAttributes: [
    "Krycie",
    "Pracowitość",
    "Współpraca",
    "Szybkość",
  ],
  keyAttributes: [
    "Dośrodkowania",
    "Odbiór piłki",
    "Przyspieszenie",
    "Wytrzymałość",
  ],
  importantAttributes: [
    "Drybling",
    "Podania",
    "Koncentracja",
    "Przewidywanie",
    "Ustawianie się",
    "Równowaga",
    "Zwinność",
  ],
  supportAttributes: [
    "Przyjęcie piłki",
    "Technika",
    "Decyzje",
    "Gra bez piłki",
  ],
},
{
  id: "inverted-wing-back-with-ball",
  name: "Odwrócony wysunięty boczny obrońca",
  positionGroup: "Wahadłowy",
  phase: "with-ball",
  coreAttributes: [
    "Podania",
    "Przewidywanie",
    "Ustawianie się",
    "Współpraca",
  ],
  keyAttributes: [
    "Odbiór piłki",
    "Decyzje",
    "Opanowanie",
    "Przyspieszenie",
  ],
  importantAttributes: [
    "Krycie",
    "Koncentracja",
    "Pracowitość",
    "Zwinność",
    "Szybkość",
  ],
  supportAttributes: [
    "Przyjęcie piłki",
    "Technika",
    "Wytrzymałość",
  ],
},

{
  id: "pressing-wing-back-without-ball",
  name: "Presujący boczny wysunięty obrońca",
  positionGroup: "Wahadłowy",
  phase: "without-ball",
  coreAttributes: [
    "Krycie",
    "Pracowitość",
    "Przewidywanie",
    "Ustawianie się",
    "Współpraca",
  ],
  keyAttributes: [
    "Odbiór piłki",
    "Agresja",
    "Przyspieszenie",
    "Wytrzymałość",
  ],
  importantAttributes: [
    "Szybkość",
    "Zwinność",
    "Koncentracja",
  ],
  supportAttributes: [
    "Decyzje",
    "Waleczność",
  ],
},
{
  id: "wing-back-without-ball",
  name: "Wysunięty boczny obrońca",
  positionGroup: "Wahadłowy",
  phase: "without-ball",
  coreAttributes: [
    "Krycie",
    "Przewidywanie",
    "Ustawianie się",
    "Współpraca",
  ],
  keyAttributes: [
    "Odbiór piłki",
    "Przyspieszenie",
    "Wytrzymałość",
  ],
  importantAttributes: [
    "Koncentracja",
    "Pracowitość",
    "Zwinność",
    "Szybkość",
  ],
  supportAttributes: [
    "Agresja",
    "Decyzje",
  ],
},
{
  id: "defensive-wing-back-without-ball",
  name: "Cofnięty wysunięty boczny obrońca",
  positionGroup: "Wahadłowy",
  phase: "without-ball",
  coreAttributes: [
    "Krycie",
    "Koncentracja",
    "Przewidywanie",
    "Ustawianie się",
  ],
  keyAttributes: [
    "Odbiór piłki",
    "Decyzje",
    "Przyspieszenie",
  ],
  importantAttributes: [
    "Szybkość",
    "Zwinność",
  ],
  supportAttributes: [
    "Współpraca",
    "Wytrzymałość",
  ],
},{
  id: "full-back-wide-playmaker-with-ball",
  name: "Rozgrywający wysunięty boczny obrońca",
  positionGroup: "Boczny obrońca",
  phase: "with-ball",
  coreAttributes: [
    "Podania",
    "Współpraca",
  ],
  keyAttributes: [
    "Odbiór piłki",
    "Przyjęcie piłki",
    "Technika",
    "Decyzje",
    "Opanowanie",
    "Przegląd sytuacji",
    "Przyspieszenie",
  ],
  importantAttributes: [
    "Drybling",
    "Krycie",
    "Koncentracja",
    "Pracowitość",
    "Przewidywanie",
    "Ustawianie się",
    "Zwinność",
    "Szybkość",
  ],
  supportAttributes: [
    "Dośrodkowania",
    "Gra bez piłki",
    "Wytrzymałość",
  ],
},
{
  id: "full-back-wing-back-with-ball",
  name: "Wysunięty boczny obrońca",
  positionGroup: "Boczny obrońca",
  phase: "with-ball",
  coreAttributes: [
    "Krycie",
    "Pracowitość",
    "Współpraca",
    "Szybkość",
  ],
  keyAttributes: [
    "Dośrodkowania",
    "Odbiór piłki",
    "Przyspieszenie",
    "Wytrzymałość",
  ],
  importantAttributes: [
    "Drybling",
    "Koncentracja",
    "Przewidywanie",
    "Ustawianie się",
    "Zwinność",
    "Równowaga",
  ],
  supportAttributes: [
    "Podania",
    "Przyjęcie piłki",
    "Technika",
    "Decyzje",
    "Gra bez piłki",
  ],
},
{
  id: "full-back-inverted-wing-back-with-ball",
  name: "Odwrócony wysunięty boczny obrońca",
  positionGroup: "Boczny obrońca",
  phase: "with-ball",
  coreAttributes: [
    "Podania",
    "Przewidywanie",
    "Ustawianie się",
    "Współpraca",
  ],
  keyAttributes: [
    "Odbiór piłki",
    "Decyzje",
    "Opanowanie",
    "Przyspieszenie",
  ],
  importantAttributes: [
    "Krycie",
    "Koncentracja",
    "Pracowitość",
    "Zwinność",
    "Szybkość",
  ],
  supportAttributes: [
    "Przyjęcie piłki",
    "Wytrzymałość",
  ],
},
{
  id: "full-back-with-ball",
  name: "Boczny obrońca",
  positionGroup: "Boczny obrońca",
  phase: "with-ball",
  coreAttributes: [
    "Krycie",
    "Koncentracja",
    "Przewidywanie",
    "Ustawianie się",
    "Współpraca",
  ],
  keyAttributes: [
    "Odbiór piłki",
    "Przyspieszenie",
  ],
  importantAttributes: [
    "Drybling",
    "Podania",
    "Szybkość",
    "Zwinność",
    "Pracowitość",
  ],
  supportAttributes: [
    "Dośrodkowania",
    "Technika",
    "Decyzje",
    "Wytrzymałość",
  ],
},
{
  id: "inverted-full-back-with-ball",
  name: "Odwrócony boczny obrońca",
  positionGroup: "Boczny obrońca",
  phase: "with-ball",
  coreAttributes: [
    "Krycie",
    "Przewidywanie",
    "Ustawianie się",
  ],
  keyAttributes: [
    "Gra głową",
    "Odbiór piłki",
    "Siła",
  ],
  importantAttributes: [
    "Drybling",
    "Koncentracja",
    "Pracowitość",
    "Zwinność",
    "Szybkość",
    "Skoczność",
  ],
  supportAttributes: [
    "Agresja",
    "Decyzje",
    "Opanowanie",
    "Waleczność",
    "Przyspieszenie",
    "Wytrzymałość",
  ],
},

{
  id: "pressing-full-back-without-ball",
  name: "Presujący boczny obrońca",
  positionGroup: "Boczny obrońca",
  phase: "without-ball",
  coreAttributes: [
    "Krycie",
    "Pracowitość",
    "Przewidywanie",
    "Ustawianie się",
    "Współpraca",
  ],
  keyAttributes: [
    "Odbiór piłki",
    "Agresja",
    "Przyspieszenie",
  ],
  importantAttributes: [
    "Koncentracja",
    "Szybkość",
    "Zwinność",
  ],
  supportAttributes: [
    "Decyzje",
    "Waleczność",
    "Wytrzymałość",
  ],
},
{
  id: "defensive-full-back-without-ball",
  name: "Cofnięty boczny obrońca",
  positionGroup: "Boczny obrońca",
  phase: "without-ball",
  coreAttributes: [
    "Krycie",
    "Koncentracja",
    "Przewidywanie",
    "Ustawianie się",
  ],
  keyAttributes: [
    "Odbiór piłki",
    "Decyzje",
    "Przyspieszenie",
  ],
  importantAttributes: [
    "Szybkość",
    "Zwinność",
    "Współpraca",
  ],
  supportAttributes: [],
},
{
  id: "full-back-without-ball",
  name: "Boczny obrońca",
  positionGroup: "Boczny obrońca",
  phase: "without-ball",
  coreAttributes: [
    "Krycie",
    "Przewidywanie",
    "Ustawianie się",
    "Współpraca",
  ],
  keyAttributes: [
    "Odbiór piłki",
    "Przyspieszenie",
  ],
  importantAttributes: [
    "Koncentracja",
    "Pracowitość",
    "Szybkość",
    "Zwinność",
  ],
  supportAttributes: [
    "Agresja",
    "Decyzje",
    "Wytrzymałość",
  ],
},
{
  id: "defensive-midfielder-with-ball",
  name: "Defensywny pomocnik",
  positionGroup: "Defensywny pomocnik",
  phase: "with-ball",
  coreAttributes: [
    "Koncentracja",
    "Przewidywanie",
    "Ustawianie się",
    "Współpraca",
  ],
  keyAttributes: [
    "Odbiór piłki",
  ],
  importantAttributes: [
    "Krycie",
    "Podania",
    "Pracowitość",
  ],
  supportAttributes: [
    "Przyjęcie piłki",
    "Agresja",
    "Decyzje",
    "Opanowanie",
    "Siła",
    "Wytrzymałość",
  ],
},
{
  id: "segundo-volante-with-ball",
  name: "Pomocnik długodystansowiec",
  positionGroup: "Defensywny pomocnik",
  phase: "with-ball",
  coreAttributes: [
    "Podania",
    "Pracowitość",
    "Współpraca",
  ],
  keyAttributes: [
    "Odbiór piłki",
    "Gra bez piłki",
    "Wytrzymałość",
  ],
  importantAttributes: [
    "Drybling",
    "Strzały z dystansu",
    "Wykańczanie akcji",
    "Przewidywanie",
    "Ustawianie się",
    "Równowaga",
    "Szybkość",
  ],
  supportAttributes: [
    "Przyjęcie piłki",
    "Technika",
    "Agresja",
    "Decyzje",
    "Opanowanie",
    "Przyspieszenie",
    "Siła",
  ],
},
{
  id: "half-back-with-ball",
  name: "Łącznik defensywy",
  positionGroup: "Defensywny pomocnik",
  phase: "with-ball",
  coreAttributes: [
    "Krycie",
    "Koncentracja",
    "Przewidywanie",
    "Ustawianie się",
    "Współpraca",
    "Skoczność",
  ],
  keyAttributes: [
    "Gra głową",
    "Odbiór piłki",
    "Siła",
  ],
  importantAttributes: [
    "Podania",
    "Pracowitość",
  ],
  supportAttributes: [
    "Przyjęcie piłki",
    "Agresja",
    "Decyzje",
    "Opanowanie",
    "Waleczność",
    "Wytrzymałość",
  ],
},
{
  id: "roaming-playmaker-dm-with-ball",
  name: "Swobodny rozgrywający",
  positionGroup: "Defensywny pomocnik",
  phase: "with-ball",
  coreAttributes: [
    "Podania",
    "Pracowitość",
    "Współpraca",
  ],
  keyAttributes: [
    "Przyjęcie piłki",
    "Technika",
    "Decyzje",
    "Gra bez piłki",
    "Opanowanie",
    "Przegląd sytuacji",
    "Wytrzymałość",
  ],
  importantAttributes: [
    "Drybling",
    "Krycie",
    "Strzały z dystansu",
    "Przewidywanie",
    "Ustawianie się",
    "Zwinność",
    "Szybkość",
    "Równowaga",
  ],
  supportAttributes: [
    "Odbiór piłki",
  ],
},
{
  id: "deep-lying-playmaker-dm-with-ball",
  name: "Cofnięty rozgrywający",
  positionGroup: "Defensywny pomocnik",
  phase: "with-ball",
  coreAttributes: [
    "Podania",
    "Współpraca",
  ],
  keyAttributes: [
    "Przyjęcie piłki",
    "Technika",
    "Decyzje",
    "Opanowanie",
    "Przegląd sytuacji",
  ],
  importantAttributes: [
    "Krycie",
    "Koncentracja",
    "Pracowitość",
    "Przewidywanie",
    "Ustawianie się",
    "Równowaga",
  ],
  supportAttributes: [
    "Odbiór piłki",
    "Gra bez piłki",
    "Wytrzymałość",
  ],
},

{
  id: "working-defensive-midfielder-without-ball",
  name: "Pracujący defensywny pomocnik",
  positionGroup: "Defensywny pomocnik",
  phase: "without-ball",
  coreAttributes: [
    "Pracowitość",
    "Przewidywanie",
    "Ustawianie się",
    "Współpraca",
  ],
  keyAttributes: [
    "Odbiór piłki",
    "Agresja",
    "Decyzje",
    "Wytrzymałość",
  ],
  importantAttributes: [
    "Koncentracja",
    "Krycie",
    "Szybkość",
  ],
  supportAttributes: [
    "Siła",
  ],
},
{
  id: "wide-covering-defensive-midfielder-without-ball",
  name: "Szeroko kryjący defensywny pomocnik",
  positionGroup: "Defensywny pomocnik",
  phase: "without-ball",
  coreAttributes: [
    "Krycie",
    "Pracowitość",
    "Przewidywanie",
    "Ustawianie się",
    "Współpraca",
    "Zwinność",
  ],
  keyAttributes: [
    "Odbiór piłki",
    "Decyzje",
    "Wytrzymałość",
  ],
  importantAttributes: [
    "Koncentracja",
    "Szybkość",
  ],
  supportAttributes: [
    "Agresja",
    "Siła",
  ],
},
{
  id: "defensive-midfielder-without-ball",
  name: "Defensywny pomocnik",
  positionGroup: "Defensywny pomocnik",
  phase: "without-ball",
  coreAttributes: [
    "Pracowitość",
    "Przewidywanie",
    "Ustawianie się",
    "Współpraca",
  ],
  keyAttributes: [
    "Odbiór piłki",
    "Decyzje",
  ],
  importantAttributes: [
    "Krycie",
    "Koncentracja",
  ],
  supportAttributes: [
    "Agresja",
    "Siła",
    "Wytrzymałość",
  ],
},
{
  id: "dropping-defensive-midfielder-without-ball",
  name: "Cofający się defensywny pomocnik",
  positionGroup: "Defensywny pomocnik",
  phase: "without-ball",
  coreAttributes: [
    "Krycie",
    "Koncentracja",
    "Pracowitość",
    "Przewidywanie",
    "Ustawianie się",
    "Współpraca",
    "Skoczność",
  ],
  keyAttributes: [
    "Odbiór piłki",
    "Decyzje",
    "Siła",
  ],
  importantAttributes: [],
  supportAttributes: [
    "Agresja",
    "Wytrzymałość",
  ],
},
{
  id: "marking-defensive-midfielder-without-ball",
  name: "Kryjący defensywny pomocnik",
  positionGroup: "Defensywny pomocnik",
  phase: "without-ball",
  coreAttributes: [
    "Krycie",
    "Koncentracja",
    "Przewidywanie",
    "Ustawianie się",
  ],
  keyAttributes: [
    "Odbiór piłki",
    "Decyzje",
  ],
  importantAttributes: [
    "Pracowitość",
    "Współpraca",
  ],
  supportAttributes: [
    "Siła",
    "Wytrzymałość",
  ],
},
{
  id: "central-midfielder-with-ball",
  name: "Środkowy pomocnik",
  positionGroup: "Środkowy pomocnik",
  phase: "with-ball",
  coreAttributes: [
    "Podania",
    "Współpraca",
  ],
  keyAttributes: [
    "Odbiór piłki",
    "Przyjęcie piłki",
    "Decyzje",
  ],
  importantAttributes: [
    "Koncentracja",
    "Pracowitość",
    "Przewidywanie",
    "Ustawianie się",
  ],
  supportAttributes: [
    "Technika",
    "Gra bez piłki",
    "Opanowanie",
    "Przegląd sytuacji",
    "Wytrzymałość",
  ],
},
{
  id: "wide-central-midfielder-with-ball",
  name: "Boczny środkowy pomocnik",
  positionGroup: "Środkowy pomocnik",
  phase: "with-ball",
  coreAttributes: [
    "Podania",
    "Współpraca",
  ],
  keyAttributes: [
    "Odbiór piłki",
    "Przyjęcie piłki",
    "Decyzje",
  ],
  importantAttributes: [
    "Drybling",
    "Koncentracja",
    "Pracowitość",
    "Przewidywanie",
    "Ustawianie się",
    "Zwinność",
  ],
  supportAttributes: [
    "Dośrodkowania",
    "Technika",
    "Gra bez piłki",
    "Opanowanie",
    "Przegląd sytuacji",
    "Wytrzymałość",
  ],
},
{
  id: "playmaker-midfielder-with-ball",
  name: "Rozgrywający pomocnik",
  positionGroup: "Środkowy pomocnik",
  phase: "with-ball",
  coreAttributes: [
    "Podania",
    "Współpraca",
  ],
  keyAttributes: [
    "Przyjęcie piłki",
    "Technika",
    "Decyzje",
    "Gra bez piłki",
    "Opanowanie",
    "Przegląd sytuacji",
  ],
  importantAttributes: [
    "Drybling",
    "Błyskotliwość",
    "Pracowitość",
    "Przewidywanie",
    "Ustawianie się",
    "Zwinność",
  ],
  supportAttributes: [
    "Odbiór piłki",
    "Wytrzymałość",
  ],
},
{
  id: "arriving-midfielder-with-ball",
  name: "Wychodzący pomocnik",
  positionGroup: "Środkowy pomocnik",
  phase: "with-ball",
  coreAttributes: [
    "Podania",
    "Pracowitość",
  ],
  keyAttributes: [
    "Dośrodkowania",
    "Przyjęcie piłki",
    "Technika",
    "Gra bez piłki",
    "Opanowanie",
    "Przyspieszenie",
  ],
  importantAttributes: [
    "Strzały z dystansu",
    "Przewidywanie",
    "Błyskotliwość",
    "Drybling",
    "Szybkość",
    "Zwinność",
  ],
  supportAttributes: [
    "Decyzje",
    "Przegląd sytuacji",
    "Wytrzymałość",
  ],
},
{
  id: "attacking-midfielder-cm-with-ball",
  name: "Ofensywny pomocnik",
  positionGroup: "Środkowy pomocnik",
  phase: "with-ball",
  coreAttributes: [
    "Podania",
    "Strzały z dystansu",
    "Błyskotliwość",
  ],
  keyAttributes: [
    "Przyjęcie piłki",
    "Technika",
    "Gra bez piłki",
    "Opanowanie",
  ],
  importantAttributes: [
    "Drybling",
    "Przewidywanie",
    "Zwinność",
  ],
  supportAttributes: [
    "Dośrodkowania",
    "Wykańczanie akcji",
    "Decyzje",
    "Przegląd sytuacji",
    "Przyspieszenie",
  ],
},
{
  id: "advanced-playmaker-cm-with-ball",
  name: "Wysunięty rozgrywający",
  positionGroup: "Środkowy pomocnik",
  phase: "with-ball",
  coreAttributes: [
    "Podania",
    "Współpraca",
  ],
  keyAttributes: [
    "Przyjęcie piłki",
    "Technika",
    "Decyzje",
    "Gra bez piłki",
    "Opanowanie",
    "Przegląd sytuacji",
  ],
  importantAttributes: [
    "Drybling",
    "Błyskotliwość",
    "Przewidywanie",
    "Zwinność",
  ],
  supportAttributes: [
    "Dośrodkowania",
    "Przyspieszenie",
  ],
},

{
  id: "pressing-central-midfielder-without-ball",
  name: "Presujący środkowy pomocnik",
  positionGroup: "Środkowy pomocnik",
  phase: "without-ball",
  coreAttributes: [
    "Pracowitość",
    "Przewidywanie",
    "Współpraca",
  ],
  keyAttributes: [
    "Odbiór piłki",
    "Agresja",
    "Decyzje",
    "Wytrzymałość",
  ],
  importantAttributes: [
    "Koncentracja",
    "Ustawianie się",
    "Szybkość",
    "Krycie",
  ],
  supportAttributes: [
    "Siła",
  ],
},
{
  id: "wide-covering-central-midfielder-without-ball",
  name: "Szeroko kryjący środkowy pomocnik",
  positionGroup: "Środkowy pomocnik",
  phase: "without-ball",
  coreAttributes: [
    "Krycie",
    "Pracowitość",
    "Współpraca",
    "Zwinność",
  ],
  keyAttributes: [
    "Odbiór piłki",
    "Decyzje",
    "Wytrzymałość",
  ],
  importantAttributes: [
    "Koncentracja",
    "Przewidywanie",
    "Ustawianie się",
    "Szybkość",
  ],
  supportAttributes: [
    "Agresja",
  ],
},
{
  id: "central-midfielder-without-ball",
  name: "Środkowy pomocnik",
  positionGroup: "Środkowy pomocnik",
  phase: "without-ball",
  coreAttributes: [
    "Pracowitość",
    "Współpraca",
  ],
  keyAttributes: [
    "Odbiór piłki",
    "Decyzje",
  ],
  importantAttributes: [
    "Krycie",
    "Koncentracja",
    "Przewidywanie",
    "Ustawianie się",
  ],
  supportAttributes: [
    "Agresja",
    "Wytrzymałość",
  ],
},
{
  id: "marking-central-midfielder-without-ball",
  name: "Kryjący środkowy pomocnik",
  positionGroup: "Środkowy pomocnik",
  phase: "without-ball",
  coreAttributes: [
    "Krycie",
    "Koncentracja",
    "Ustawianie się",
  ],
  keyAttributes: [
    "Odbiór piłki",
    "Decyzje",
  ],
  importantAttributes: [
    "Pracowitość",
    "Przewidywanie",
    "Współpraca",
  ],
  supportAttributes: [
    "Wytrzymałość",
  ],
},
{
  id: "attacking-midfielder-am-with-ball",
  name: "Ofensywny pomocnik",
  positionGroup: "Ofensywny pomocnik",
  phase: "with-ball",
  coreAttributes: [
    "Podania",
    "Strzały z dystansu",
    "Błyskotliwość",
  ],
  keyAttributes: [
    "Przyjęcie piłki",
    "Technika",
    "Gra bez piłki",
    "Opanowanie",
  ],
  importantAttributes: [
    "Drybling",
    "Wykańczanie akcji",
    "Przewidywanie",
    "Zwinność",
  ],
  supportAttributes: [
    "Dośrodkowania",
    "Decyzje",
    "Przegląd sytuacji",
    "Przyspieszenie",
  ],
},
{
  id: "free-role-am-with-ball",
  name: "Wolna rola",
  positionGroup: "Ofensywny pomocnik",
  phase: "with-ball",
  coreAttributes: [
    "Błyskotliwość",
    "Drybling",
    "Podania",
    "Strzały z dystansu",
  ],
  keyAttributes: [
    "Przyjęcie piłki",
    "Technika",
    "Gra bez piłki",
    "Opanowanie",
    "Przegląd sytuacji",
  ],
  importantAttributes: [
    "Wykańczanie akcji",
    "Przewidywanie",
    "Zwinność",
  ],
  supportAttributes: [
    "Dośrodkowania",
    "Decyzje",
    "Przyspieszenie",
  ],
},
{
  id: "advanced-playmaker-am-with-ball",
  name: "Wysunięty rozgrywający",
  positionGroup: "Ofensywny pomocnik",
  phase: "with-ball",
  coreAttributes: [
    "Podania",
    "Współpraca",
  ],
  keyAttributes: [
    "Przyjęcie piłki",
    "Technika",
    "Decyzje",
    "Gra bez piłki",
    "Opanowanie",
    "Przegląd sytuacji",
  ],
  importantAttributes: [
    "Drybling",
    "Błyskotliwość",
    "Przewidywanie",
    "Zwinność",
  ],
  supportAttributes: [
    "Dośrodkowania",
    "Przyspieszenie",
  ],
},
{
  id: "arriving-midfielder-am-with-ball",
  name: "Wychodzący pomocnik",
  positionGroup: "Ofensywny pomocnik",
  phase: "with-ball",
  coreAttributes: [
    "Podania",
    "Pracowitość",
  ],
  keyAttributes: [
    "Dośrodkowania",
    "Przyjęcie piłki",
    "Technika",
    "Gra bez piłki",
    "Opanowanie",
    "Przyspieszenie",
  ],
  importantAttributes: [
    "Błyskotliwość",
    "Przewidywanie",
    "Szybkość",
    "Zwinność",
  ],
  supportAttributes: [
    "Drybling",
    "Strzały z dystansu",
    "Decyzje",
    "Przegląd sytuacji",
    "Wytrzymałość",
  ],
},
{
  id: "false-forward-am-with-ball",
  name: "Fałszywy napastnik",
  positionGroup: "Ofensywny pomocnik",
  phase: "with-ball",
  coreAttributes: [
    "Wykańczanie akcji",
    "Przewidywanie",
    "Przyspieszenie",
  ],
  keyAttributes: [
    "Przyjęcie piłki",
    "Gra bez piłki",
    "Opanowanie",
  ],
  importantAttributes: [
    "Drybling",
    "Podania",
    "Strzały z dystansu",
    "Pracowitość",
    "Koncentracja",
    "Szybkość",
    "Zwinność",
  ],
  supportAttributes: [
    "Technika",
    "Decyzje",
    "Wytrzymałość",
  ],
},

{
  id: "attacking-midfielder-am-without-ball",
  name: "Ofensywny pomocnik",
  positionGroup: "Ofensywny pomocnik",
  phase: "without-ball",
  coreAttributes: [
    "Przewidywanie",
    "Pracowitość",
  ],
  keyAttributes: [
    "Decyzje",
  ],
  importantAttributes: [
    "Krycie",
    "Współpraca",
  ],
  supportAttributes: [
    "Agresja",
    "Gra bez piłki",
    "Wytrzymałość",
  ],
},
{
  id: "hanging-receiving-am-without-ball",
  name: "Podwieszony przyjmujący ofensywny pomocnik",
  positionGroup: "Ofensywny pomocnik",
  phase: "without-ball",
  coreAttributes: [
    "Koncentracja",
    "Szybkość",
    "Przewidywanie",
    "Współpraca",
  ],
  keyAttributes: [
    "Decyzje",
    "Gra bez piłki",
  ],
  importantAttributes: [
    "Krycie",
  ],
  supportAttributes: [
    "Przyjęcie piłki",
    "Opanowanie",
    "Przyspieszenie",
  ],
},
{
  id: "central-receiving-am-without-ball",
  name: "Centrujący przyjmujący ofensywny pomocnik",
  positionGroup: "Ofensywny pomocnik",
  phase: "without-ball",
  coreAttributes: [
    "Koncentracja",
    "Przewidywanie",
    "Współpraca",
    "Równowaga",
  ],
  keyAttributes: [
    "Decyzje",
    "Gra bez piłki",
  ],
  importantAttributes: [
    "Krycie",
  ],
  supportAttributes: [
    "Przyjęcie piłki",
    "Opanowanie",
    "Siła",
  ],
},
{
  id: "tracking-am-without-ball",
  name: "Śledzący ofensywny pomocnik",
  positionGroup: "Ofensywny pomocnik",
  phase: "without-ball",
  coreAttributes: [
    "Pracowitość",
    "Przewidywanie",
    "Współpraca",
  ],
  keyAttributes: [
    "Agresja",
    "Decyzje",
    "Wytrzymałość",
  ],
  importantAttributes: [
    "Ustawianie się",
    "Krycie",
  ],
  supportAttributes: [
    "Gra bez piłki",
  ],
},
{
  id: "ball-playing-centre-back-with-ball",
  name: "Grający piłką środkowy obrońca",
  positionGroup: "Środkowy obrońca",
  phase: "with-ball",
  coreAttributes: [
    "Krycie",
    "Podania",
    "Przewidywanie",
    "Ustawianie się",
    "Skoczność",
  ],
  keyAttributes: [
    "Gra głową",
    "Odbiór piłki",
    "Przyjęcie piłki",
    "Technika",
    "Decyzje",
    "Opanowanie",
    "Siła",
  ],
  importantAttributes: [
    "Koncentracja",
    "Szybkość",
  ],
  supportAttributes: [
    "Agresja",
    "Waleczność",
    "Przyspieszenie",
  ],
},
{
  id: "overlapping-centre-back-with-ball",
  name: "Obiegający środkowy obrońca",
  positionGroup: "Środkowy obrońca",
  phase: "with-ball",
  coreAttributes: [
    "Krycie",
    "Pracowitość",
    "Przewidywanie",
    "Skoczność",
    "Szybkość",
  ],
  keyAttributes: [
    "Gra głową",
    "Odbiór piłki",
    "Podania",
    "Przyjęcie piłki",
    "Decyzje",
    "Siła",
    "Wytrzymałość",
  ],
  importantAttributes: [
    "Drybling",
    "Koncentracja",
    "Ustawianie się",
    "Zwinność",
  ],
  supportAttributes: [
    "Technika",
    "Agresja",
    "Opanowanie",
    "Waleczność",
    "Przyspieszenie",
  ],
},
{
  id: "advanced-centre-back-with-ball",
  name: "Zaawansowany środkowy obrońca",
  positionGroup: "Środkowy obrońca",
  phase: "with-ball",
  coreAttributes: [
    "Krycie",
    "Podania",
    "Przewidywanie",
    "Ustawianie się",
    "Współpraca",
    "Skoczność",
  ],
  keyAttributes: [
    "Gra głową",
    "Odbiór piłki",
    "Przyjęcie piłki",
    "Technika",
    "Decyzje",
    "Opanowanie",
    "Siła",
  ],
  importantAttributes: [
    "Drybling",
    "Koncentracja",
    "Szybkość",
  ],
  supportAttributes: [
    "Agresja",
    "Waleczność",
    "Przyspieszenie",
  ],
},
{
  id: "traditional-centre-back-with-ball",
  name: "Tradycyjny środkowy obrońca",
  positionGroup: "Środkowy obrońca",
  phase: "with-ball",
  coreAttributes: [
    "Krycie",
    "Skoczność",
    "Przewidywanie",
    "Ustawianie się",
  ],
  keyAttributes: [
    "Gra głową",
    "Odbiór piłki",
    "Agresja",
    "Siła",
  ],
  importantAttributes: [
    "Szybkość",
    "Koncentracja",
  ],
  supportAttributes: [
    "Decyzje",
    "Waleczność",
    "Przyspieszenie",
  ],
},
{
  id: "centre-back-with-ball",
  name: "Środkowy obrońca",
  positionGroup: "Środkowy obrońca",
  phase: "with-ball",
  coreAttributes: [
    "Krycie",
    "Skoczność",
    "Przewidywanie",
    "Ustawianie się",
  ],
  keyAttributes: [
    "Gra głową",
    "Odbiór piłki",
    "Decyzje",
    "Siła",
  ],
  importantAttributes: [
    "Koncentracja",
    "Szybkość",
  ],
  supportAttributes: [
    "Agresja",
    "Opanowanie",
    "Waleczność",
    "Przyspieszenie",
  ],
},
{
  id: "wide-centre-back-with-ball",
  name: "Boczny środkowy obrońca",
  positionGroup: "Środkowy obrońca",
  phase: "with-ball",
  coreAttributes: [
    "Krycie",
    "Przewidywanie",
    "Ustawianie się",
    "Skoczność",
  ],
  keyAttributes: [
    "Gra głową",
    "Odbiór piłki",
    "Podania",
    "Przyjęcie piłki",
    "Decyzje",
    "Siła",
  ],
  importantAttributes: [
    "Drybling",
    "Koncentracja",
    "Pracowitość",
    "Szybkość",
    "Zwinność",
  ],
  supportAttributes: [
    "Technika",
    "Agresja",
    "Opanowanie",
    "Waleczność",
    "Przyspieszenie",
    "Wytrzymałość",
  ],
},

{
  id: "blocking-wide-centre-back-without-ball",
  name: "Blokujący boczny środkowy obrońca",
  positionGroup: "Środkowy obrońca",
  phase: "without-ball",
  coreAttributes: [
    "Krycie",
    "Skoczność",
    "Przewidywanie",
    "Ustawianie się",
  ],
  keyAttributes: [
    "Gra głową",
    "Odbiór piłki",
    "Siła",
  ],
  importantAttributes: [
    "Koncentracja",
    "Szybkość",
    "Zwinność",
  ],
  supportAttributes: [
    "Agresja",
    "Decyzje",
    "Waleczność",
    "Przyspieszenie",
  ],
},
{
  id: "wide-centre-back-without-ball",
  name: "Boczny środkowy obrońca",
  positionGroup: "Środkowy obrońca",
  phase: "without-ball",
  coreAttributes: [
    "Krycie",
    "Przewidywanie",
    "Ustawianie się",
    "Skoczność",
  ],
  keyAttributes: [
    "Gra głową",
    "Odbiór piłki",
    "Decyzje",
    "Siła",
  ],
  importantAttributes: [
    "Zwinność",
    "Szybkość",
    "Koncentracja",
    "Waleczność",
  ],
  supportAttributes: [
    "Agresja",
    "Przyspieszenie",
  ],
},
{
  id: "blocking-centre-back-without-ball",
  name: "Blokujący środkowy obrońca",
  positionGroup: "Środkowy obrońca",
  phase: "without-ball",
  coreAttributes: [
    "Krycie",
    "Przewidywanie",
    "Ustawianie się",
    "Skoczność",
  ],
  keyAttributes: [
    "Gra głową",
    "Odbiór piłki",
    "Siła",
  ],
  importantAttributes: [
    "Koncentracja",
    "Szybkość",
  ],
  supportAttributes: [
    "Agresja",
    "Decyzje",
    "Waleczność",
    "Przyspieszenie",
  ],
},
{
  id: "centre-back-without-ball",
  name: "Środkowy obrońca",
  positionGroup: "Środkowy obrońca",
  phase: "without-ball",
  coreAttributes: [
    "Krycie",
    "Przewidywanie",
    "Ustawianie się",
    "Skoczność",
  ],
  keyAttributes: [
    "Gra głową",
    "Odbiór piłki",
    "Decyzje",
    "Siła",
  ],
  importantAttributes: [
    "Koncentracja",
    "Szybkość",
  ],
  supportAttributes: [
    "Agresja",
    "Waleczność",
    "Przyspieszenie",
  ],
},
{
  id: "covering-wide-centre-back-without-ball",
  name: "Asekurujący boczny środkowy obrońca",
  positionGroup: "Środkowy obrońca",
  phase: "without-ball",
  coreAttributes: [
    "Krycie",
    "Koncentracja",
    "Przewidywanie",
    "Ustawianie się",
    "Szybkość",
    "Skoczność",
  ],
  keyAttributes: [
    "Gra głową",
    "Odbiór piłki",
    "Decyzje",
    "Przyspieszenie",
  ],
  importantAttributes: [
    "Zwinność",
  ],
  supportAttributes: [
    "Agresja",
    "Waleczność",
    "Siła",
  ],
},
{
  id: "covering-centre-back-without-ball",
  name: "Asekurujący środkowy obrońca",
  positionGroup: "Środkowy obrońca",
  phase: "without-ball",
  coreAttributes: [
    "Krycie",
    "Koncentracja",
    "Przewidywanie",
    "Ustawianie się",
    "Szybkość",
    "Skoczność",
  ],
  keyAttributes: [
    "Gra głową",
    "Odbiór piłki",
    "Decyzje",
    "Przyspieszenie",
  ],
  importantAttributes: [],
  supportAttributes: [
    "Agresja",
    "Waleczność",
    "Siła",
    "Zwinność",
  ],
},
{
  id: "goalkeeper-playing-with-ball",
  name: "Bramkarz grający piłką",
  positionGroup: "Bramkarz",
  phase: "with-ball",
  coreAttributes: [
    "Chwytanie",
    "Gra na przedpolu",
    "Komunikacja",
    "Refleks",
    "Wykopy",
    "Zasięg wyskoku",
  ],
  keyAttributes: [
    "Zwinność",
    "Koncentracja",
    "Ustawianie się",
  ],
  importantAttributes: [
    "Podania",
    "Opanowanie",
    "Decyzje",
  ],
  supportAttributes: [
    "Ekscentryczność",
    "Jeden na jednego",
    "Wyrzuty",
    "Przewidywanie",
  ],
},
{
  id: "traditional-goalkeeper-with-ball",
  name: "Tradycyjny bramkarz",
  positionGroup: "Bramkarz",
  phase: "with-ball",
  coreAttributes: [
    "Chwytanie",
    "Gra na przedpolu",
    "Komunikacja",
    "Refleks",
    "Zasięg wyskoku",
  ],
  keyAttributes: [
    "Koncentracja",
    "Ustawianie się",
    "Zwinność",
  ],
  importantAttributes: [
    "Decyzje",
  ],
  supportAttributes: [
    "Jeden na jednego",
    "Przewidywanie",
  ],
},
{
  id: "goalkeeper-with-ball",
  name: "Bramkarz",
  positionGroup: "Bramkarz",
  phase: "with-ball",
  coreAttributes: [
    "Chwytanie",
    "Gra na przedpolu",
    "Komunikacja",
    "Refleks",
    "Zasięg wyskoku",
  ],
  keyAttributes: [
    "Koncentracja",
    "Ustawianie się",
    "Zwinność",
  ],
  importantAttributes: [
    "Wykopy",
    "Decyzje",
  ],
  supportAttributes: [
    "Jeden na jednego",
    "Wyrzuty",
    "Przewidywanie",
  ],
},
{
  id: "goalkeeper-without-ball",
  name: "Bramkarz",
  positionGroup: "Bramkarz",
  phase: "without-ball",
  coreAttributes: [
    "Chwytanie",
    "Gra na przedpolu",
    "Komunikacja",
    "Refleks",
    "Zasięg wyskoku",
  ],
  keyAttributes: [
    "Koncentracja",
    "Ustawianie się",
    "Zwinność",
  ],
  importantAttributes: [
    "Decyzje",
  ],
  supportAttributes: [
    "Jeden na jednego",
    "Wychodzenie poza pole karne",
    "Przewidywanie",
  ],
},
{
  id: "sweeper-goalkeeper-without-ball",
  name: "Bramkarz-libero",
  positionGroup: "Bramkarz",
  phase: "without-ball",
  coreAttributes: [
    "Chwytanie",
    "Gra na przedpolu",
    "Komunikacja",
    "Refleks",
    "Zasięg wyskoku",
    "Decyzje",
  ],
  keyAttributes: [
    "Jeden na jednego",
    "Wychodzenie poza pole karne",
    "Przewidywanie",
    "Zwinność",
  ],
  importantAttributes: [
    "Przyspieszenie",
  ],
  supportAttributes: [
    "Ekscentryczność",
    "Koncentracja",
    "Ustawianie się",
  ],
},
{
  id: "line-goalkeeper-without-ball",
  name: "Bramkarz grający na linii",
  positionGroup: "Bramkarz",
  phase: "without-ball",
  coreAttributes: [
    "Chwytanie",
    "Gra na przedpolu",
    "Komunikacja",
    "Refleks",
    "Zasięg wyskoku",
  ],
  keyAttributes: [
    "Koncentracja",
    "Ustawianie się",
    "Zwinność",
  ],
  importantAttributes: [
    "Decyzje",
  ],
  supportAttributes: [
    "Jeden na jednego",
    "Przewidywanie",
  ],
},
];

export const GOALKEEPER_ROLES: RoleDefinition[] = ROLE_DEFINITIONS.filter(
  (role) => role.positionGroup === "Bramkarz"
);

  export const STRIKER_ROLES: RoleDefinition[] = ROLE_DEFINITIONS.filter(
  (role) => role.positionGroup === "Napastnik"
);

export function getRolePhaseLabel(phase: RolePhase): string {
  if (phase === "with-ball") {
    return "przy piłce";
  }

  return "bez piłki";
}

export function getRoleAttributeImportance(
  role: RoleDefinition | null,
  attribute: string
): RoleImportance | null {
  if (!role) {
    return null;
  }

  if (role.coreAttributes?.includes(attribute)) {
    return "core";
  }

  if (role.keyAttributes.includes(attribute)) {
    return "key";
  }

  if (role.importantAttributes.includes(attribute)) {
    return "important";
  }

  if (role.supportAttributes?.includes(attribute)) {
    return "support";
  }

  return null;
}