import type {
  FootRequirement,
  FormationPreset,
  PitchPosition,
} from "../types/squadBuilderTypes";

export const FOOT_REQUIREMENTS: { id: FootRequirement; label: string }[] = [
  { id: "any", label: "Dowolna noga" },
  { id: "left-decent", label: "Lewa min. przyzwoita" },
  { id: "left-strong", label: "Lewa min. względnie mocna" },
  { id: "left-high", label: "Lewa min. wysoka" },
  { id: "left-dominant", label: "Lewonożny" },
  { id: "right-decent", label: "Prawa min. przyzwoita" },
  { id: "right-strong", label: "Prawa min. względnie mocna" },
  { id: "right-high", label: "Prawa min. wysoka" },
  { id: "right-dominant", label: "Prawonożny" },
  { id: "both-decent", label: "Obie min. przyzwoite" },
  { id: "both-strong", label: "Obie min. względnie mocne" },
];

export const FORMATION_PRESETS: FormationPreset[] = [
  {
    id: "4231",
    name: "4-2-3-1",
    slots: [
      {
        id: "ST",
        label: "N",
        line: "Atak",
        positionGroup: "Napastnik",
        phase: "with-ball",
        roleId: "best",
        footRequirement: "any",
      },
      {
        id: "LW",
        label: "LS",
        line: "Pomoc",
        positionGroup: "Skrzydłowy",
        phase: "with-ball",
        roleId: "best",
        footRequirement: "any",
      },
      {
        id: "AM",
        label: "OP",
        line: "Pomoc",
        positionGroup: "Ofensywny pomocnik",
        phase: "with-ball",
        roleId: "best",
        footRequirement: "any",
      },
      {
        id: "RW",
        label: "PS",
        line: "Pomoc",
        positionGroup: "Skrzydłowy",
        phase: "with-ball",
        roleId: "best",
        footRequirement: "any",
      },
      {
        id: "DM1",
        label: "LDP",
        line: "Pomoc",
        positionGroup: "Defensywny pomocnik",
        phase: "without-ball",
        roleId: "best",
        footRequirement: "any",
      },
      {
        id: "DM2",
        label: "PDP",
        line: "Pomoc",
        positionGroup: "Defensywny pomocnik",
        phase: "with-ball",
        roleId: "best",
        footRequirement: "any",
      },
      {
        id: "LB",
        label: "LO",
        line: "Obrona",
        positionGroup: "Boczny obrońca",
        phase: "with-ball",
        roleId: "best",
        footRequirement: "left-decent",
      },
      {
        id: "LCB",
        label: "LŚO",
        line: "Obrona",
        positionGroup: "Środkowy obrońca",
        phase: "with-ball",
        roleId: "best",
        footRequirement: "left-strong",
      },
      {
        id: "RCB",
        label: "PŚO",
        line: "Obrona",
        positionGroup: "Środkowy obrońca",
        phase: "without-ball",
        roleId: "best",
        footRequirement: "any",
      },
      {
        id: "RB",
        label: "PO",
        line: "Obrona",
        positionGroup: "Boczny obrońca",
        phase: "with-ball",
        roleId: "best",
        footRequirement: "right-decent",
      },
    ],
  },
  {
    id: "433dm",
    name: "4-3-3 z DP",
    slots: [
      {
        id: "ST",
        label: "N",
        line: "Atak",
        positionGroup: "Napastnik",
        phase: "with-ball",
        roleId: "best",
        footRequirement: "any",
      },
      {
        id: "LW",
        label: "LS",
        line: "Atak",
        positionGroup: "Skrzydłowy",
        phase: "with-ball",
        roleId: "best",
        footRequirement: "any",
      },
      {
        id: "RW",
        label: "PS",
        line: "Atak",
        positionGroup: "Skrzydłowy",
        phase: "with-ball",
        roleId: "best",
        footRequirement: "any",
      },
      {
        id: "LCM",
        label: "LŚP",
        line: "Pomoc",
        positionGroup: "Środkowy pomocnik",
        phase: "with-ball",
        roleId: "best",
        footRequirement: "any",
      },
      {
        id: "RCM",
        label: "PŚP",
        line: "Pomoc",
        positionGroup: "Środkowy pomocnik",
        phase: "without-ball",
        roleId: "best",
        footRequirement: "any",
      },
      {
        id: "DM",
        label: "DP",
        line: "Pomoc",
        positionGroup: "Defensywny pomocnik",
        phase: "without-ball",
        roleId: "best",
        footRequirement: "any",
      },
      {
        id: "LB",
        label: "LO",
        line: "Obrona",
        positionGroup: "Boczny obrońca",
        phase: "with-ball",
        roleId: "best",
        footRequirement: "left-decent",
      },
      {
        id: "LCB",
        label: "LŚO",
        line: "Obrona",
        positionGroup: "Środkowy obrońca",
        phase: "with-ball",
        roleId: "best",
        footRequirement: "left-strong",
      },
      {
        id: "RCB",
        label: "PŚO",
        line: "Obrona",
        positionGroup: "Środkowy obrońca",
        phase: "without-ball",
        roleId: "best",
        footRequirement: "any",
      },
      {
        id: "RB",
        label: "PO",
        line: "Obrona",
        positionGroup: "Boczny obrońca",
        phase: "with-ball",
        roleId: "best",
        footRequirement: "right-decent",
      },
    ],
  },
  {
    id: "3421",
    name: "3-4-2-1",
    slots: [
      {
        id: "ST",
        label: "N",
        line: "Atak",
        positionGroup: "Napastnik",
        phase: "with-ball",
        roleId: "best",
        footRequirement: "any",
      },
      {
        id: "LAM",
        label: "LOP",
        line: "Atak",
        positionGroup: "Ofensywny pomocnik",
        phase: "with-ball",
        roleId: "best",
        footRequirement: "any",
      },
      {
        id: "RAM",
        label: "POP",
        line: "Atak",
        positionGroup: "Ofensywny pomocnik",
        phase: "with-ball",
        roleId: "best",
        footRequirement: "any",
      },
      {
        id: "LWB",
        label: "LW",
        line: "Pomoc",
        positionGroup: "Wahadłowy",
        phase: "with-ball",
        roleId: "best",
        footRequirement: "left-decent",
      },
      {
        id: "LCM",
        label: "LŚP",
        line: "Pomoc",
        positionGroup: "Środkowy pomocnik",
        phase: "with-ball",
        roleId: "best",
        footRequirement: "any",
      },
      {
        id: "RCM",
        label: "PŚP",
        line: "Pomoc",
        positionGroup: "Środkowy pomocnik",
        phase: "without-ball",
        roleId: "best",
        footRequirement: "any",
      },
      {
        id: "RWB",
        label: "PW",
        line: "Pomoc",
        positionGroup: "Wahadłowy",
        phase: "with-ball",
        roleId: "best",
        footRequirement: "right-decent",
      },
      {
        id: "LCB",
        label: "LŚO",
        line: "Obrona",
        positionGroup: "Środkowy obrońca",
        phase: "with-ball",
        roleId: "best",
        footRequirement: "left-strong",
      },
      {
        id: "CB",
        label: "ŚO",
        line: "Obrona",
        positionGroup: "Środkowy obrońca",
        phase: "without-ball",
        roleId: "best",
        footRequirement: "any",
      },
      {
        id: "RCB",
        label: "PŚO",
        line: "Obrona",
        positionGroup: "Środkowy obrońca",
        phase: "with-ball",
        roleId: "best",
        footRequirement: "right-decent",
      },
    ],
  },
  {
    id: "442",
    name: "4-4-2 / 4-2-2-2",
    slots: [
      {
        id: "ST1",
        label: "LN",
        line: "Atak",
        positionGroup: "Napastnik",
        phase: "with-ball",
        roleId: "best",
        footRequirement: "any",
      },
      {
        id: "ST2",
        label: "PN",
        line: "Atak",
        positionGroup: "Napastnik",
        phase: "with-ball",
        roleId: "best",
        footRequirement: "any",
      },
      {
        id: "LM",
        label: "LP",
        line: "Pomoc",
        positionGroup: "Boczny pomocnik",
        phase: "with-ball",
        roleId: "best",
        footRequirement: "left-decent",
      },
      {
        id: "LCM",
        label: "LŚP",
        line: "Pomoc",
        positionGroup: "Środkowy pomocnik",
        phase: "without-ball",
        roleId: "best",
        footRequirement: "any",
      },
      {
        id: "RCM",
        label: "PŚP",
        line: "Pomoc",
        positionGroup: "Środkowy pomocnik",
        phase: "with-ball",
        roleId: "best",
        footRequirement: "any",
      },
      {
        id: "RM",
        label: "PP",
        line: "Pomoc",
        positionGroup: "Boczny pomocnik",
        phase: "with-ball",
        roleId: "best",
        footRequirement: "right-decent",
      },
      {
        id: "LB",
        label: "LO",
        line: "Obrona",
        positionGroup: "Boczny obrońca",
        phase: "without-ball",
        roleId: "best",
        footRequirement: "left-decent",
      },
      {
        id: "LCB",
        label: "LŚO",
        line: "Obrona",
        positionGroup: "Środkowy obrońca",
        phase: "with-ball",
        roleId: "best",
        footRequirement: "left-strong",
      },
      {
        id: "RCB",
        label: "PŚO",
        line: "Obrona",
        positionGroup: "Środkowy obrońca",
        phase: "without-ball",
        roleId: "best",
        footRequirement: "any",
      },
      {
        id: "RB",
        label: "PO",
        line: "Obrona",
        positionGroup: "Boczny obrońca",
        phase: "without-ball",
        roleId: "best",
        footRequirement: "right-decent",
      },
    ],
  },
    {
    id: "4141",
    name: "4-1-4-1",
    slots: [
      {
        id: "ST",
        label: "N",
        line: "Atak",
        positionGroup: "Napastnik",
        phase: "without-ball",
        roleId: "best",
        footRequirement: "any",
      },
      {
        id: "LM",
        label: "LP",
        line: "Pomoc",
        positionGroup: "Boczny pomocnik",
        phase: "without-ball",
        roleId: "best",
        footRequirement: "left-decent",
      },
      {
        id: "LCM",
        label: "LŚP",
        line: "Pomoc",
        positionGroup: "Środkowy pomocnik",
        phase: "without-ball",
        roleId: "best",
        footRequirement: "any",
      },
      {
        id: "RCM",
        label: "PŚP",
        line: "Pomoc",
        positionGroup: "Środkowy pomocnik",
        phase: "without-ball",
        roleId: "best",
        footRequirement: "any",
      },
      {
        id: "RM",
        label: "PP",
        line: "Pomoc",
        positionGroup: "Boczny pomocnik",
        phase: "without-ball",
        roleId: "best",
        footRequirement: "right-decent",
      },
      {
        id: "DM",
        label: "DP",
        line: "Pomoc",
        positionGroup: "Defensywny pomocnik",
        phase: "without-ball",
        roleId: "best",
        footRequirement: "any",
      },
      {
        id: "LB",
        label: "LO",
        line: "Obrona",
        positionGroup: "Boczny obrońca",
        phase: "without-ball",
        roleId: "best",
        footRequirement: "left-decent",
      },
      {
        id: "LCB",
        label: "LŚO",
        line: "Obrona",
        positionGroup: "Środkowy obrońca",
        phase: "without-ball",
        roleId: "best",
        footRequirement: "left-strong",
      },
      {
        id: "RCB",
        label: "PŚO",
        line: "Obrona",
        positionGroup: "Środkowy obrońca",
        phase: "without-ball",
        roleId: "best",
        footRequirement: "any",
      },
      {
        id: "RB",
        label: "PO",
        line: "Obrona",
        positionGroup: "Boczny obrońca",
        phase: "without-ball",
        roleId: "best",
        footRequirement: "right-decent",
      },
    ],
  },
];

export const PITCH_POSITIONS: Record<string, Record<string, PitchPosition>> = {
  "4231": {
    ST: { x: 50, y: 13 },
    LW: { x: 22, y: 29 },
    AM: { x: 50, y: 30 },
    RW: { x: 78, y: 29 },
    DM1: { x: 40, y: 52 },
    DM2: { x: 60, y: 52 },
    LB: { x: 16, y: 78 },
    LCB: { x: 38, y: 81 },
    RCB: { x: 62, y: 81 },
    RB: { x: 84, y: 78 },
  },

"433dm": {
  ST: { x: 50, y: 13 },
  LW: { x: 20, y: 23 },
  RW: { x: 80, y: 23 },

  LCM: { x: 30, y: 43 },
  RCM: { x: 70, y: 43 },
  DM: { x: 50, y: 61 },

  LB: { x: 15, y: 80 },
  LCB: { x: 37, y: 82 },
  RCB: { x: 63, y: 82 },
  RB: { x: 85, y: 80 },
},

  "3421": {
    ST: { x: 50, y: 12 },
    LAM: { x: 38, y: 28 },
    RAM: { x: 62, y: 28 },
    LWB: { x: 15, y: 48 },
    LCM: { x: 40, y: 52 },
    RCM: { x: 60, y: 52 },
    RWB: { x: 85, y: 48 },
    LCB: { x: 32, y: 80 },
    CB: { x: 50, y: 84 },
    RCB: { x: 68, y: 80 },
  },

  "442": {
    ST1: { x: 42, y: 13 },
    ST2: { x: 58, y: 13 },
    LM: { x: 18, y: 43 },
    LCM: { x: 40, y: 48 },
    RCM: { x: 60, y: 48 },
    RM: { x: 82, y: 43 },
    LB: { x: 16, y: 80 },
    LCB: { x: 38, y: 82 },
    RCB: { x: 62, y: 82 },
    RB: { x: 84, y: 80 },
  },
    "4141": {
    ST: { x: 50, y: 13 },

    LM: { x: 17, y: 40 },
    LCM: { x: 38, y: 42 },
    RCM: { x: 62, y: 42 },
    RM: { x: 83, y: 40 },

    DM: { x: 50, y: 58 },

    LB: { x: 16, y: 74 },
    LCB: { x: 38, y: 76 },
    RCB: { x: 62, y: 76 },
    RB: { x: 84, y: 74 },
  },
};