import type {
  FootRequirement,
  FormationLine,
  FormationPreset,
  PitchPosition,
  SlotSide,
} from "../types/squadBuilderTypes";
import type { FormationSlot } from "../types/squadBuilderTypes";

export const FOOT_REQUIREMENTS: { id: FootRequirement; label: string }[] = [
  { id: "any", label: "Dowolna noga" },
  { id: "left-decent", label: "Lewa min. przyzwoita" },
  { id: "left-strong", label: "Lewa min. względnie mocna" },
  { id: "left-high", label: "Lewa min. wysoka" },
  { id: "left-dominant", label: "Lewonożny" },
  { id: "right-decent", label: "Prawa min. przyzwoita" },
  { id: "right-strong", label: "Prawa min. względnie mocna" },
  { id: "right-high", label: "Prawa min. wysoka" },
  { id: "right-dominant", label: "Prawonożny" },
  { id: "both-decent", label: "Obie min. przyzwoite" },
  { id: "both-strong", label: "Obie min. względnie mocne" },
];

function slot(
  id: string,
  label: string,
  line: FormationLine,
  positionGroup: string,
  side: SlotSide = "center",
  footRequirement: FootRequirement = "any"
): FormationSlot {
  return {
    id,
    label,
    line,
    positionGroup,
    side,
    phase: "with-ball",
    roleId: "best",
    footRequirement,
  };
}

const GK = slot("GK", "BR", "Obrona", "Bramkarz");
const ST = slot("ST", "N", "Atak", "Napastnik");
const ST1 = slot("ST1", "LN", "Atak", "Napastnik", "center");
const ST2 = slot("ST2", "PN", "Atak", "Napastnik", "center");

export const FORMATION_PRESETS: FormationPreset[] = [
  {
    id: "4231",
    name: "4-2-3-1",
    slots: [
      ST,
      slot("LW", "LS", "Pomoc", "Skrzydłowy", "left"),
      slot("AM", "OP", "Pomoc", "Ofensywny pomocnik"),
      slot("RW", "PS", "Pomoc", "Skrzydłowy", "right"),
      slot("DM1", "LDP", "Pomoc", "Defensywny pomocnik"),
      slot("DM2", "PDP", "Pomoc", "Defensywny pomocnik"),
      slot("LB", "LO", "Obrona", "Boczny obrońca", "left", "left-decent"),
      slot("LCB", "LŚO", "Obrona", "Środkowy obrońca", "left", "left-strong"),
      slot("RCB", "PŚO", "Obrona", "Środkowy obrońca", "right"),
      slot("RB", "PO", "Obrona", "Boczny obrońca", "right", "right-decent"),
      GK,
    ],
  },
  {
    id: "4231narrow",
    name: "4-2-3-1 Wąsko",
    slots: [
      ST,
      slot("LAM", "LOP", "Atak", "Ofensywny pomocnik", "left"),
      slot("AM", "OP", "Atak", "Ofensywny pomocnik"),
      slot("RAM", "POP", "Atak", "Ofensywny pomocnik", "right"),
      slot("DM1", "LDP", "Pomoc", "Defensywny pomocnik"),
      slot("DM2", "PDP", "Pomoc", "Defensywny pomocnik"),
      slot("LB", "LO", "Obrona", "Boczny obrońca", "left", "left-decent"),
      slot("LCB", "LŚO", "Obrona", "Środkowy obrońca", "left", "left-strong"),
      slot("RCB", "PŚO", "Obrona", "Środkowy obrońca", "right"),
      slot("RB", "PO", "Obrona", "Boczny obrońca", "right", "right-decent"),
      GK,
    ],
  },
  {
    id: "433dm",
    name: "4-3-3 z DP",
    slots: [
      ST,
      slot("LW", "LS", "Atak", "Skrzydłowy", "left"),
      slot("RW", "PS", "Atak", "Skrzydłowy", "right"),
      slot("LCM", "LŚP", "Pomoc", "Środkowy pomocnik"),
      slot("RCM", "PŚP", "Pomoc", "Środkowy pomocnik"),
      slot("DM", "DP", "Pomoc", "Defensywny pomocnik"),
      slot("LB", "LO", "Obrona", "Boczny obrońca", "left", "left-decent"),
      slot("LCB", "LŚO", "Obrona", "Środkowy obrońca", "left", "left-strong"),
      slot("RCB", "PŚO", "Obrona", "Środkowy obrońca", "right"),
      slot("RB", "PO", "Obrona", "Boczny obrońca", "right", "right-decent"),
      GK,
    ],
  },
  {
    id: "433dmwide",
    name: "4-3-3 DP Szeroko",
    slots: [
      ST,
      slot("LW", "LS", "Atak", "Skrzydłowy", "left"),
      slot("RW", "PS", "Atak", "Skrzydłowy", "right"),
      slot("LCM", "LŚP", "Pomoc", "Środkowy pomocnik", "left"),
      slot("RCM", "PŚP", "Pomoc", "Środkowy pomocnik", "right"),
      slot("DM", "DP", "Pomoc", "Defensywny pomocnik"),
      slot("LB", "LO", "Obrona", "Boczny obrońca", "left", "left-decent"),
      slot("LCB", "LŚO", "Obrona", "Środkowy obrońca", "left", "left-strong"),
      slot("RCB", "PŚO", "Obrona", "Środkowy obrońca", "right"),
      slot("RB", "PO", "Obrona", "Boczny obrońca", "right", "right-decent"),
      GK,
    ],
  },
  {
    id: "433",
    name: "4-3-3 bez DP",
    slots: [
      ST,
      slot("LW", "LS", "Atak", "Skrzydłowy", "left"),
      slot("RW", "PS", "Atak", "Skrzydłowy", "right"),
      slot("LCM", "LŚP", "Pomoc", "Środkowy pomocnik"),
      slot("CM", "ŚP", "Pomoc", "Środkowy pomocnik"),
      slot("RCM", "PŚP", "Pomoc", "Środkowy pomocnik"),
      slot("LB", "LO", "Obrona", "Boczny obrońca", "left", "left-decent"),
      slot("LCB", "LŚO", "Obrona", "Środkowy obrońca", "left", "left-strong"),
      slot("RCB", "PŚO", "Obrona", "Środkowy obrońca", "right"),
      slot("RB", "PO", "Obrona", "Boczny obrońca", "right", "right-decent"),
      GK,
    ],
  },
  {
    id: "4141",
    name: "4-1-4-1",
    slots: [
      ST,
      slot("LM", "LP", "Pomoc", "Boczny pomocnik", "left"),
      slot("LCM", "LŚP", "Pomoc", "Środkowy pomocnik"),
      slot("RCM", "PŚP", "Pomoc", "Środkowy pomocnik"),
      slot("RM", "PP", "Pomoc", "Boczny pomocnik", "right"),
      slot("DM", "DP", "Pomoc", "Defensywny pomocnik"),
      slot("LB", "LO", "Obrona", "Boczny obrońca", "left", "left-decent"),
      slot("LCB", "LŚO", "Obrona", "Środkowy obrońca", "left", "left-strong"),
      slot("RCB", "PŚO", "Obrona", "Środkowy obrońca", "right"),
      slot("RB", "PO", "Obrona", "Boczny obrońca", "right", "right-decent"),
      GK,
    ],
  },
  {
    id: "4411",
    name: "4-4-1-1",
    slots: [
      ST,
      slot("AM", "OP", "Atak", "Ofensywny pomocnik"),
      slot("LM", "LP", "Pomoc", "Boczny pomocnik", "left", "left-decent"),
      slot("LCM", "LŚP", "Pomoc", "Środkowy pomocnik"),
      slot("RCM", "PŚP", "Pomoc", "Środkowy pomocnik"),
      slot("RM", "PP", "Pomoc", "Boczny pomocnik", "right", "right-decent"),
      slot("LB", "LO", "Obrona", "Boczny obrońca", "left", "left-decent"),
      slot("LCB", "LŚO", "Obrona", "Środkowy obrońca", "left", "left-strong"),
      slot("RCB", "PŚO", "Obrona", "Środkowy obrońca", "right"),
      slot("RB", "PO", "Obrona", "Boczny obrońca", "right", "right-decent"),
      GK,
    ],
  },
  {
    id: "4411dm",
    name: "4-4-1-1 DP",
    slots: [
      ST,
      slot("AM", "OP", "Atak", "Ofensywny pomocnik"),
      slot("LM", "LP", "Pomoc", "Boczny pomocnik", "left", "left-decent"),
      slot("LCM", "LŚP", "Pomoc", "Środkowy pomocnik"),
      slot("DM", "DP", "Pomoc", "Defensywny pomocnik"),
      slot("RM", "PP", "Pomoc", "Boczny pomocnik", "right", "right-decent"),
      slot("LB", "LO", "Obrona", "Boczny obrońca", "left", "left-decent"),
      slot("LCB", "LŚO", "Obrona", "Środkowy obrońca", "left", "left-strong"),
      slot("RCB", "PŚO", "Obrona", "Środkowy obrońca", "right"),
      slot("RB", "PO", "Obrona", "Boczny obrońca", "right", "right-decent"),
      GK,
    ],
  },
  {
    id: "442",
    name: "4-4-2",
    slots: [
      ST1,
      ST2,
      slot("LM", "LP", "Pomoc", "Boczny pomocnik", "left", "left-decent"),
      slot("LCM", "LŚP", "Pomoc", "Środkowy pomocnik"),
      slot("RCM", "PŚP", "Pomoc", "Środkowy pomocnik"),
      slot("RM", "PP", "Pomoc", "Boczny pomocnik", "right", "right-decent"),
      slot("LB", "LO", "Obrona", "Boczny obrońca", "left", "left-decent"),
      slot("LCB", "LŚO", "Obrona", "Środkowy obrońca", "left", "left-strong"),
      slot("RCB", "PŚO", "Obrona", "Środkowy obrońca", "right"),
      slot("RB", "PO", "Obrona", "Boczny obrońca", "right", "right-decent"),
      GK,
    ],
  },
  {
    id: "442diamond",
    name: "4-4-2 Diament wąsko",
    slots: [
      ST1,
      ST2,
      slot("AM", "OP", "Atak", "Ofensywny pomocnik"),
      slot("LCM", "LŚP", "Pomoc", "Środkowy pomocnik", "left"),
      slot("RCM", "PŚP", "Pomoc", "Środkowy pomocnik", "right"),
      slot("DM", "DP", "Pomoc", "Defensywny pomocnik"),
      slot("LB", "LO", "Obrona", "Boczny obrońca", "left", "left-decent"),
      slot("LCB", "LŚO", "Obrona", "Środkowy obrońca", "left", "left-strong"),
      slot("RCB", "PŚO", "Obrona", "Środkowy obrońca", "right"),
      slot("RB", "PO", "Obrona", "Boczny obrońca", "right", "right-decent"),
      GK,
    ],
  },
  {
    id: "4222",
    name: "4-2-2-2",
    slots: [
      ST1,
      ST2,
      slot("LAM", "LOP", "Pomoc", "Ofensywny pomocnik", "left"),
      slot("RAM", "POP", "Pomoc", "Ofensywny pomocnik", "right"),
      slot("LCM", "LŚP", "Pomoc", "Środkowy pomocnik"),
      slot("RCM", "PŚP", "Pomoc", "Środkowy pomocnik"),
      slot("LB", "LO", "Obrona", "Boczny obrońca", "left", "left-decent"),
      slot("LCB", "LŚO", "Obrona", "Środkowy obrońca", "left", "left-strong"),
      slot("RCB", "PŚO", "Obrona", "Środkowy obrońca", "right"),
      slot("RB", "PO", "Obrona", "Boczny obrońca", "right", "right-decent"),
      GK,
    ],
  },
  {
    id: "4222dmwide",
    name: "4-2-2-2 DP Szeroko",
    slots: [
      ST1,
      ST2,
      slot("LW", "LS", "Atak", "Skrzydłowy", "left"),
      slot("RW", "PS", "Atak", "Skrzydłowy", "right"),
      slot("LDM", "LDP", "Pomoc", "Defensywny pomocnik"),
      slot("RDM", "PDP", "Pomoc", "Defensywny pomocnik"),
      slot("LB", "LO", "Obrona", "Boczny obrońca", "left", "left-decent"),
      slot("LCB", "LŚO", "Obrona", "Środkowy obrońca", "left", "left-strong"),
      slot("RCB", "PŚO", "Obrona", "Środkowy obrońca", "right"),
      slot("RB", "PO", "Obrona", "Boczny obrońca", "right", "right-decent"),
      GK,
    ],
  },
  {
    id: "424dmwide",
    name: "4-2-4 DP Szeroko",
    slots: [
      ST1,
      ST2,
      slot("LW", "LS", "Atak", "Skrzydłowy", "left"),
      slot("RW", "PS", "Atak", "Skrzydłowy", "right"),
      slot("LDM", "LDP", "Pomoc", "Defensywny pomocnik"),
      slot("RDM", "PDP", "Pomoc", "Defensywny pomocnik"),
      slot("LB", "LO", "Obrona", "Boczny obrońca", "left", "left-decent"),
      slot("LCB", "LŚO", "Obrona", "Środkowy obrońca", "left", "left-strong"),
      slot("RCB", "PŚO", "Obrona", "Środkowy obrońca", "right"),
      slot("RB", "PO", "Obrona", "Boczny obrońca", "right", "right-decent"),
      GK,
    ],
  },
  {
    id: "352",
    name: "3-5-2",
    slots: [
      ST1,
      ST2,
      slot("LWB", "LW", "Pomoc", "Wahadłowy", "left", "left-decent"),
      slot("LCM", "LŚP", "Pomoc", "Środkowy pomocnik"),
      slot("CM", "ŚP", "Pomoc", "Środkowy pomocnik"),
      slot("RCM", "PŚP", "Pomoc", "Środkowy pomocnik"),
      slot("RWB", "PW", "Pomoc", "Wahadłowy", "right", "right-decent"),
      slot("LCB", "LŚO", "Obrona", "Środkowy obrońca", "left", "left-strong"),
      slot("CB", "ŚO", "Obrona", "Środkowy obrońca"),
      slot("RCB", "PŚO", "Obrona", "Środkowy obrońca", "right", "right-decent"),
      GK,
    ],
  },
  {
    id: "3412",
    name: "3-4-1-2",
    slots: [
      ST1,
      ST2,
      slot("AM", "OP", "Atak", "Ofensywny pomocnik"),
      slot("LWB", "LW", "Pomoc", "Wahadłowy", "left", "left-decent"),
      slot("LCM", "LŚP", "Pomoc", "Środkowy pomocnik"),
      slot("RCM", "PŚP", "Pomoc", "Środkowy pomocnik"),
      slot("RWB", "PW", "Pomoc", "Wahadłowy", "right", "right-decent"),
      slot("LCB", "LŚO", "Obrona", "Środkowy obrońca", "left", "left-strong"),
      slot("CB", "ŚO", "Obrona", "Środkowy obrońca"),
      slot("RCB", "PŚO", "Obrona", "Środkowy obrońca", "right", "right-decent"),
      GK,
    ],
  },
  {
    id: "3421",
    name: "3-4-2-1",
    slots: [
      ST,
      slot("LAM", "LOP", "Atak", "Ofensywny pomocnik", "left"),
      slot("RAM", "POP", "Atak", "Ofensywny pomocnik", "right"),
      slot("LWB", "LW", "Pomoc", "Wahadłowy", "left", "left-decent"),
      slot("LCM", "LŚP", "Pomoc", "Środkowy pomocnik"),
      slot("RCM", "PŚP", "Pomoc", "Środkowy pomocnik"),
      slot("RWB", "PW", "Pomoc", "Wahadłowy", "right", "right-decent"),
      slot("LCB", "LŚO", "Obrona", "Środkowy obrońca", "left", "left-strong"),
      slot("CB", "ŚO", "Obrona", "Środkowy obrońca"),
      slot("RCB", "PŚO", "Obrona", "Środkowy obrońca", "right", "right-decent"),
      GK,
    ],
  },
  {
    id: "343",
    name: "3-4-3",
    slots: [
      ST,
      slot("LW", "LS", "Atak", "Skrzydłowy", "left"),
      slot("RW", "PS", "Atak", "Skrzydłowy", "right"),
      slot("LWB", "LW", "Pomoc", "Wahadłowy", "left", "left-decent"),
      slot("LCM", "LŚP", "Pomoc", "Środkowy pomocnik"),
      slot("RCM", "PŚP", "Pomoc", "Środkowy pomocnik"),
      slot("RWB", "PW", "Pomoc", "Wahadłowy", "right", "right-decent"),
      slot("LCB", "LŚO", "Obrona", "Środkowy obrońca", "left", "left-strong"),
      slot("CB", "ŚO", "Obrona", "Środkowy obrońca"),
      slot("RCB", "PŚO", "Obrona", "Środkowy obrońca", "right", "right-decent"),
      GK,
    ],
  },
  {
    id: "343dmwide",
    name: "3-4-3 DP Szeroko",
    slots: [
      ST,
      slot("LW", "LS", "Atak", "Skrzydłowy", "left"),
      slot("RW", "PS", "Atak", "Skrzydłowy", "right"),
      slot("LWB", "LW", "Pomoc", "Wahadłowy", "left", "left-decent"),
      slot("LDM", "LDP", "Pomoc", "Defensywny pomocnik"),
      slot("RDM", "PDP", "Pomoc", "Defensywny pomocnik"),
      slot("RWB", "PW", "Pomoc", "Wahadłowy", "right", "right-decent"),
      slot("LCB", "LŚO", "Obrona", "Środkowy obrońca", "left", "left-strong"),
      slot("CB", "ŚO", "Obrona", "Środkowy obrońca"),
      slot("RCB", "PŚO", "Obrona", "Środkowy obrońca", "right", "right-decent"),
      GK,
    ],
  },
  {
    id: "343dmnarrow",
    name: "3-4-3 DP Wąsko",
    slots: [
      ST,
      slot("LAM", "LOP", "Atak", "Ofensywny pomocnik", "left"),
      slot("RAM", "POP", "Atak", "Ofensywny pomocnik", "right"),
      slot("LWB", "LW", "Pomoc", "Wahadłowy", "left", "left-decent"),
      slot("LDM", "LDP", "Pomoc", "Defensywny pomocnik"),
      slot("RDM", "PDP", "Pomoc", "Defensywny pomocnik"),
      slot("RWB", "PW", "Pomoc", "Wahadłowy", "right", "right-decent"),
      slot("LCB", "LŚO", "Obrona", "Środkowy obrońca", "left", "left-strong"),
      slot("CB", "ŚO", "Obrona", "Środkowy obrońca"),
      slot("RCB", "PŚO", "Obrona", "Środkowy obrońca", "right", "right-decent"),
      GK,
    ],
  },
  {
    id: "3241",
    name: "3-2-4-1",
    slots: [
      ST,
      slot("LAM", "LOP", "Atak", "Ofensywny pomocnik", "left"),
      slot("RAM", "POP", "Atak", "Ofensywny pomocnik", "right"),
      slot("LM", "LP", "Pomoc", "Boczny pomocnik", "left"),
      slot("RM", "PP", "Pomoc", "Boczny pomocnik", "right"),
      slot("LDM", "LDP", "Pomoc", "Defensywny pomocnik"),
      slot("RDM", "PDP", "Pomoc", "Defensywny pomocnik"),
      slot("LCB", "LŚO", "Obrona", "Środkowy obrońca", "left", "left-strong"),
      slot("CB", "ŚO", "Obrona", "Środkowy obrońca"),
      slot("RCB", "PŚO", "Obrona", "Środkowy obrońca", "right", "right-decent"),
      GK,
    ],
  },
  {
    id: "532",
    name: "5-3-2",
    slots: [
      ST1,
      ST2,
      slot("LCM", "LŚP", "Pomoc", "Środkowy pomocnik"),
      slot("CM", "ŚP", "Pomoc", "Środkowy pomocnik"),
      slot("RCM", "PŚP", "Pomoc", "Środkowy pomocnik"),
      slot("LWB", "LO", "Obrona", "Boczny obrońca", "left", "left-decent"),
      slot("LCB", "LŚO", "Obrona", "Środkowy obrońca", "left", "left-strong"),
      slot("CB", "ŚO", "Obrona", "Środkowy obrońca"),
      slot("RCB", "PŚO", "Obrona", "Środkowy obrońca", "right", "right-decent"),
      slot("RWB", "PO", "Obrona", "Boczny obrońca", "right", "right-decent"),
      GK,
    ],
  },
  {
    id: "523",
    name: "5-2-3 / 3-4-3 defensywne",
    slots: [
      ST,
      slot("LW", "LS", "Atak", "Skrzydłowy", "left"),
      slot("RW", "PS", "Atak", "Skrzydłowy", "right"),
      slot("LCM", "LŚP", "Pomoc", "Środkowy pomocnik"),
      slot("RCM", "PŚP", "Pomoc", "Środkowy pomocnik"),
      slot("LWB", "LO", "Obrona", "Boczny obrońca", "left", "left-decent"),
      slot("LCB", "LŚO", "Obrona", "Środkowy obrońca", "left", "left-strong"),
      slot("CB", "ŚO", "Obrona", "Środkowy obrońca"),
      slot("RCB", "PŚO", "Obrona", "Środkowy obrońca", "right", "right-decent"),
      slot("RWB", "PO", "Obrona", "Boczny obrońca", "right", "right-decent"),
      GK,
    ],
  },
  {
    id: "5212dmwo",
    name: "5-2-1-2 DP WO",
    slots: [
      ST1,
      ST2,
      slot("AM", "OP", "Atak", "Ofensywny pomocnik"),
      slot("LDM", "LDP", "Pomoc", "Defensywny pomocnik"),
      slot("RDM", "PDP", "Pomoc", "Defensywny pomocnik"),
      slot("LWB", "LO", "Obrona", "Boczny obrońca", "left", "left-decent"),
      slot("LCB", "LŚO", "Obrona", "Środkowy obrońca", "left", "left-strong"),
      slot("CB", "ŚO", "Obrona", "Środkowy obrońca"),
      slot("RCB", "PŚO", "Obrona", "Środkowy obrońca", "right", "right-decent"),
      slot("RWB", "PO", "Obrona", "Boczny obrońca", "right", "right-decent"),
      GK,
    ],
  },
  {
    id: "5122dmwo",
    name: "5-1-2-2 DP WO",
    slots: [
      ST1,
      ST2,
      slot("LCM", "LŚP", "Pomoc", "Środkowy pomocnik"),
      slot("RCM", "PŚP", "Pomoc", "Środkowy pomocnik"),
      slot("DM", "DP", "Pomoc", "Defensywny pomocnik"),
      slot("LWB", "LO", "Obrona", "Boczny obrońca", "left", "left-decent"),
      slot("LCB", "LŚO", "Obrona", "Środkowy obrońca", "left", "left-strong"),
      slot("CB", "ŚO", "Obrona", "Środkowy obrońca"),
      slot("RCB", "PŚO", "Obrona", "Środkowy obrońca", "right", "right-decent"),
      slot("RWB", "PO", "Obrona", "Boczny obrońca", "right", "right-decent"),
      GK,
    ],
  },
  {
    id: "4213dmwide",
    name: "4-2-1-3 DP Szeroko",
    slots: [
      ST,
      slot("LW", "LS", "Atak", "Skrzydłowy", "left"),
      slot("AM", "OP", "Atak", "Ofensywny pomocnik"),
      slot("RW", "PS", "Atak", "Skrzydłowy", "right"),
      slot("LDM", "LDP", "Pomoc", "Defensywny pomocnik"),
      slot("RDM", "PDP", "Pomoc", "Defensywny pomocnik"),
      slot("LB", "LO", "Obrona", "Boczny obrońca", "left", "left-decent"),
      slot("LCB", "LŚO", "Obrona", "Środkowy obrońca", "left", "left-strong"),
      slot("RCB", "PŚO", "Obrona", "Środkowy obrońca", "right"),
      slot("RB", "PO", "Obrona", "Boczny obrońca", "right", "right-decent"),
      GK,
    ],
  },
  {
    id: "4312dmnarrow",
    name: "4-3-1-2 DP Wąsko",
    slots: [
      ST1,
      ST2,
      slot("AM", "OP", "Atak", "Ofensywny pomocnik"),
      slot("LCM", "LŚP", "Pomoc", "Środkowy pomocnik"),
      slot("RCM", "PŚP", "Pomoc", "Środkowy pomocnik"),
      slot("DM", "DP", "Pomoc", "Defensywny pomocnik"),
      slot("LB", "LO", "Obrona", "Boczny obrońca", "left", "left-decent"),
      slot("LCB", "LŚO", "Obrona", "Środkowy obrońca", "left", "left-strong"),
      slot("RCB", "PŚO", "Obrona", "Środkowy obrońca", "right"),
      slot("RB", "PO", "Obrona", "Boczny obrońca", "right", "right-decent"),
      GK,
    ],
  },
  {
    id: "442dmwide",
    name: "4-4-2 DP Szeroko",
    slots: [
      ST1,
      ST2,
      slot("LM", "LP", "Pomoc", "Boczny pomocnik", "left"),
      slot("LDM", "LDP", "Pomoc", "Defensywny pomocnik"),
      slot("RDM", "PDP", "Pomoc", "Defensywny pomocnik"),
      slot("RM", "PP", "Pomoc", "Boczny pomocnik", "right"),
      slot("LB", "LO", "Obrona", "Boczny obrońca", "left", "left-decent"),
      slot("LCB", "LŚO", "Obrona", "Środkowy obrońca", "left", "left-strong"),
      slot("RCB", "PŚO", "Obrona", "Środkowy obrońca", "right"),
      slot("RB", "PO", "Obrona", "Boczny obrońca", "right", "right-decent"),
      GK,
    ],
  },
  {
    id: "3142dmwo",
    name: "3-1-4-2 DP WO",
    slots: [
      ST1,
      ST2,
      slot("LWB", "LW", "Pomoc", "Wahadłowy", "left", "left-decent"),
      slot("LCM", "LŚP", "Pomoc", "Środkowy pomocnik"),
      slot("RCM", "PŚP", "Pomoc", "Środkowy pomocnik"),
      slot("RWB", "PW", "Pomoc", "Wahadłowy", "right", "right-decent"),
      slot("DM", "DP", "Pomoc", "Defensywny pomocnik"),
      slot("LCB", "LŚO", "Obrona", "Środkowy obrońca", "left", "left-strong"),
      slot("CB", "ŚO", "Obrona", "Środkowy obrońca"),
      slot("RCB", "PŚO", "Obrona", "Środkowy obrońca", "right", "right-decent"),
      GK,
    ],
  },
  {
    id: "5221wo",
    name: "5-2-2-1 WO",
    slots: [
      ST,
      slot("LAM", "LOP", "Atak", "Ofensywny pomocnik", "left"),
      slot("RAM", "POP", "Atak", "Ofensywny pomocnik", "right"),
      slot("LCM", "LŚP", "Pomoc", "Środkowy pomocnik"),
      slot("RCM", "PŚP", "Pomoc", "Środkowy pomocnik"),
      slot("LWB", "LO", "Obrona", "Boczny obrońca", "left", "left-decent"),
      slot("LCB", "LŚO", "Obrona", "Środkowy obrońca", "left", "left-strong"),
      slot("CB", "ŚO", "Obrona", "Środkowy obrońca"),
      slot("RCB", "PŚO", "Obrona", "Środkowy obrońca", "right", "right-decent"),
      slot("RWB", "PO", "Obrona", "Boczny obrońca", "right", "right-decent"),
      GK,
    ],
  },
];

export const PITCH_POSITIONS: Record<string, Record<string, PitchPosition>> = {
  "4231": {
    ST: { x: 50, y: 13 }, LW: { x: 22, y: 29 }, AM: { x: 50, y: 30 }, RW: { x: 78, y: 29 },
    DM1: { x: 40, y: 52 }, DM2: { x: 60, y: 52 },
    LB: { x: 16, y: 78 }, LCB: { x: 38, y: 81 }, RCB: { x: 62, y: 81 }, RB: { x: 84, y: 78 }, GK: { x: 50, y: 92 },
  },
  "4231narrow": {
    ST: { x: 50, y: 12 }, LAM: { x: 36, y: 28 }, AM: { x: 50, y: 31 }, RAM: { x: 64, y: 28 },
    DM1: { x: 40, y: 55 }, DM2: { x: 60, y: 55 },
    LB: { x: 15, y: 80 }, LCB: { x: 37, y: 82 }, RCB: { x: 63, y: 82 }, RB: { x: 85, y: 80 }, GK: { x: 50, y: 92 },
  },
  "433dm": {
    ST: { x: 50, y: 13 }, LW: { x: 20, y: 23 }, RW: { x: 80, y: 23 },
    LCM: { x: 30, y: 43 }, RCM: { x: 70, y: 43 }, DM: { x: 50, y: 61 },
    LB: { x: 15, y: 80 }, LCB: { x: 37, y: 82 }, RCB: { x: 63, y: 82 }, RB: { x: 85, y: 80 }, GK: { x: 50, y: 92 },
  },
  "433dmwide": {
    ST: { x: 50, y: 12 }, LW: { x: 18, y: 23 }, RW: { x: 82, y: 23 },
    LCM: { x: 34, y: 44 }, RCM: { x: 66, y: 44 }, DM: { x: 50, y: 61 },
    LB: { x: 15, y: 80 }, LCB: { x: 37, y: 82 }, RCB: { x: 63, y: 82 }, RB: { x: 85, y: 80 }, GK: { x: 50, y: 92 },
  },
  "433": {
    ST: { x: 50, y: 13 }, LW: { x: 20, y: 23 }, RW: { x: 80, y: 23 },
    LCM: { x: 30, y: 47 }, CM: { x: 50, y: 50 }, RCM: { x: 70, y: 47 },
    LB: { x: 15, y: 80 }, LCB: { x: 37, y: 82 }, RCB: { x: 63, y: 82 }, RB: { x: 85, y: 80 }, GK: { x: 50, y: 92 },
  },
  "4141": {
    ST: { x: 50, y: 13 }, LM: { x: 17, y: 40 }, LCM: { x: 38, y: 42 }, RCM: { x: 62, y: 42 }, RM: { x: 83, y: 40 },
    DM: { x: 50, y: 58 }, LB: { x: 16, y: 74 }, LCB: { x: 38, y: 76 }, RCB: { x: 62, y: 76 }, RB: { x: 84, y: 74 }, GK: { x: 50, y: 91 },
  },
  "4411": {
    ST: { x: 50, y: 12 }, AM: { x: 50, y: 28 }, LM: { x: 18, y: 43 }, LCM: { x: 40, y: 48 }, RCM: { x: 60, y: 48 }, RM: { x: 82, y: 43 },
    LB: { x: 16, y: 80 }, LCB: { x: 38, y: 82 }, RCB: { x: 62, y: 82 }, RB: { x: 84, y: 80 }, GK: { x: 50, y: 92 },
  },
  "4411dm": {
    ST: { x: 50, y: 12 }, AM: { x: 50, y: 28 }, LM: { x: 18, y: 43 }, LCM: { x: 40, y: 48 }, DM: { x: 60, y: 55 }, RM: { x: 82, y: 43 },
    LB: { x: 16, y: 80 }, LCB: { x: 38, y: 82 }, RCB: { x: 62, y: 82 }, RB: { x: 84, y: 80 }, GK: { x: 50, y: 92 },
  },
  "442": {
    ST1: { x: 42, y: 13 }, ST2: { x: 58, y: 13 }, LM: { x: 18, y: 43 }, LCM: { x: 40, y: 48 }, RCM: { x: 60, y: 48 }, RM: { x: 82, y: 43 },
    LB: { x: 16, y: 80 }, LCB: { x: 38, y: 82 }, RCB: { x: 62, y: 82 }, RB: { x: 84, y: 80 }, GK: { x: 50, y: 92 },
  },
  "442diamond": {
    ST1: { x: 42, y: 12 }, ST2: { x: 58, y: 12 }, AM: { x: 50, y: 31 }, LCM: { x: 38, y: 48 }, RCM: { x: 62, y: 48 }, DM: { x: 50, y: 61 },
    LB: { x: 15, y: 80 }, LCB: { x: 37, y: 82 }, RCB: { x: 63, y: 82 }, RB: { x: 85, y: 80 }, GK: { x: 50, y: 92 },
  },
  "4222": {
    ST1: { x: 42, y: 13 }, ST2: { x: 58, y: 13 }, LAM: { x: 34, y: 32 }, RAM: { x: 66, y: 32 }, LCM: { x: 40, y: 54 }, RCM: { x: 60, y: 54 },
    LB: { x: 16, y: 80 }, LCB: { x: 38, y: 82 }, RCB: { x: 62, y: 82 }, RB: { x: 84, y: 80 }, GK: { x: 50, y: 92 },
  },
  "4222dmwide": {
    ST1: { x: 42, y: 12 }, ST2: { x: 58, y: 12 }, LW: { x: 20, y: 29 }, RW: { x: 80, y: 29 }, LDM: { x: 40, y: 57 }, RDM: { x: 60, y: 57 },
    LB: { x: 15, y: 80 }, LCB: { x: 37, y: 82 }, RCB: { x: 63, y: 82 }, RB: { x: 85, y: 80 }, GK: { x: 50, y: 92 },
  },
  "424dmwide": {
    ST1: { x: 42, y: 12 }, ST2: { x: 58, y: 12 }, LW: { x: 18, y: 26 }, RW: { x: 82, y: 26 }, LDM: { x: 40, y: 58 }, RDM: { x: 60, y: 58 },
    LB: { x: 15, y: 80 }, LCB: { x: 37, y: 82 }, RCB: { x: 63, y: 82 }, RB: { x: 85, y: 80 }, GK: { x: 50, y: 92 },
  },
  "352": {
    ST1: { x: 42, y: 12 }, ST2: { x: 58, y: 12 }, LWB: { x: 14, y: 45 }, LCM: { x: 34, y: 48 }, CM: { x: 50, y: 53 }, RCM: { x: 66, y: 48 }, RWB: { x: 86, y: 45 },
    LCB: { x: 31, y: 80 }, CB: { x: 50, y: 84 }, RCB: { x: 69, y: 80 }, GK: { x: 50, y: 93 },
  },
  "3412": {
    ST1: { x: 42, y: 12 }, ST2: { x: 58, y: 12 }, AM: { x: 50, y: 29 }, LWB: { x: 15, y: 49 }, LCM: { x: 40, y: 53 }, RCM: { x: 60, y: 53 }, RWB: { x: 85, y: 49 },
    LCB: { x: 31, y: 80 }, CB: { x: 50, y: 84 }, RCB: { x: 69, y: 80 }, GK: { x: 50, y: 93 },
  },
  "3421": {
    ST: { x: 50, y: 12 }, LAM: { x: 38, y: 28 }, RAM: { x: 62, y: 28 }, LWB: { x: 15, y: 48 }, LCM: { x: 40, y: 52 }, RCM: { x: 60, y: 52 }, RWB: { x: 85, y: 48 },
    LCB: { x: 32, y: 80 }, CB: { x: 50, y: 84 }, RCB: { x: 68, y: 80 }, GK: { x: 50, y: 93 },
  },
  "343": {
    ST: { x: 50, y: 12 }, LW: { x: 24, y: 24 }, RW: { x: 76, y: 24 }, LWB: { x: 15, y: 48 }, LCM: { x: 40, y: 52 }, RCM: { x: 60, y: 52 }, RWB: { x: 85, y: 48 },
    LCB: { x: 32, y: 80 }, CB: { x: 50, y: 84 }, RCB: { x: 68, y: 80 }, GK: { x: 50, y: 93 },
  },
  "343dmwide": {
    ST: { x: 50, y: 12 }, LW: { x: 22, y: 24 }, RW: { x: 78, y: 24 }, LWB: { x: 14, y: 46 }, LDM: { x: 40, y: 55 }, RDM: { x: 60, y: 55 }, RWB: { x: 86, y: 46 },
    LCB: { x: 31, y: 80 }, CB: { x: 50, y: 84 }, RCB: { x: 69, y: 80 }, GK: { x: 50, y: 93 },
  },
  "343dmnarrow": {
    ST: { x: 50, y: 12 }, LAM: { x: 38, y: 27 }, RAM: { x: 62, y: 27 }, LWB: { x: 14, y: 47 }, LDM: { x: 40, y: 56 }, RDM: { x: 60, y: 56 }, RWB: { x: 86, y: 47 },
    LCB: { x: 31, y: 80 }, CB: { x: 50, y: 84 }, RCB: { x: 69, y: 80 }, GK: { x: 50, y: 93 },
  },
  "3241": {
    ST: { x: 50, y: 12 }, LAM: { x: 38, y: 27 }, RAM: { x: 62, y: 27 }, LM: { x: 18, y: 42 }, RM: { x: 82, y: 42 }, LDM: { x: 40, y: 57 }, RDM: { x: 60, y: 57 },
    LCB: { x: 31, y: 80 }, CB: { x: 50, y: 84 }, RCB: { x: 69, y: 80 }, GK: { x: 50, y: 93 },
  },
  "532": {
    ST1: { x: 42, y: 13 }, ST2: { x: 58, y: 13 }, LCM: { x: 34, y: 45 }, CM: { x: 50, y: 50 }, RCM: { x: 66, y: 45 },
    LWB: { x: 14, y: 70 }, LCB: { x: 31, y: 79 }, CB: { x: 50, y: 83 }, RCB: { x: 69, y: 79 }, RWB: { x: 86, y: 70 }, GK: { x: 50, y: 93 },
  },
  "523": {
    ST: { x: 50, y: 13 }, LW: { x: 22, y: 26 }, RW: { x: 78, y: 26 }, LCM: { x: 41, y: 50 }, RCM: { x: 59, y: 50 },
    LWB: { x: 14, y: 70 }, LCB: { x: 31, y: 79 }, CB: { x: 50, y: 83 }, RCB: { x: 69, y: 79 }, RWB: { x: 86, y: 70 }, GK: { x: 50, y: 93 },
  },
  "5212dmwo": {
    ST1: { x: 42, y: 12 }, ST2: { x: 58, y: 12 }, AM: { x: 50, y: 29 }, LDM: { x: 40, y: 54 }, RDM: { x: 60, y: 54 },
    LWB: { x: 14, y: 70 }, LCB: { x: 31, y: 79 }, CB: { x: 50, y: 83 }, RCB: { x: 69, y: 79 }, RWB: { x: 86, y: 70 }, GK: { x: 50, y: 93 },
  },
  "5122dmwo": {
    ST1: { x: 42, y: 12 }, ST2: { x: 58, y: 12 }, LCM: { x: 38, y: 45 }, RCM: { x: 62, y: 45 }, DM: { x: 50, y: 58 },
    LWB: { x: 14, y: 70 }, LCB: { x: 31, y: 79 }, CB: { x: 50, y: 83 }, RCB: { x: 69, y: 79 }, RWB: { x: 86, y: 70 }, GK: { x: 50, y: 93 },
  },
  "4213dmwide": {
    ST: { x: 50, y: 12 }, LW: { x: 20, y: 24 }, AM: { x: 50, y: 28 }, RW: { x: 80, y: 24 }, LDM: { x: 40, y: 55 }, RDM: { x: 60, y: 55 },
    LB: { x: 15, y: 80 }, LCB: { x: 37, y: 82 }, RCB: { x: 63, y: 82 }, RB: { x: 85, y: 80 }, GK: { x: 50, y: 92 },
  },
  "4312dmnarrow": {
    ST1: { x: 42, y: 12 }, ST2: { x: 58, y: 12 }, AM: { x: 50, y: 30 }, LCM: { x: 36, y: 47 }, RCM: { x: 64, y: 47 }, DM: { x: 50, y: 60 },
    LB: { x: 15, y: 80 }, LCB: { x: 37, y: 82 }, RCB: { x: 63, y: 82 }, RB: { x: 85, y: 80 }, GK: { x: 50, y: 92 },
  },
  "442dmwide": {
    ST1: { x: 42, y: 13 }, ST2: { x: 58, y: 13 }, LM: { x: 18, y: 43 }, LDM: { x: 40, y: 57 }, RDM: { x: 60, y: 57 }, RM: { x: 82, y: 43 },
    LB: { x: 16, y: 80 }, LCB: { x: 38, y: 82 }, RCB: { x: 62, y: 82 }, RB: { x: 84, y: 80 }, GK: { x: 50, y: 92 },
  },
  "3142dmwo": {
    ST1: { x: 42, y: 12 }, ST2: { x: 58, y: 12 }, LWB: { x: 15, y: 45 }, LCM: { x: 38, y: 47 }, RCM: { x: 62, y: 47 }, RWB: { x: 85, y: 45 }, DM: { x: 50, y: 61 },
    LCB: { x: 31, y: 80 }, CB: { x: 50, y: 84 }, RCB: { x: 69, y: 80 }, GK: { x: 50, y: 93 },
  },
  "5221wo": {
    ST: { x: 50, y: 12 }, LAM: { x: 38, y: 29 }, RAM: { x: 62, y: 29 }, LCM: { x: 40, y: 50 }, RCM: { x: 60, y: 50 },
    LWB: { x: 14, y: 70 }, LCB: { x: 31, y: 79 }, CB: { x: 50, y: 83 }, RCB: { x: 69, y: 79 }, RWB: { x: 86, y: 70 }, GK: { x: 50, y: 93 },
  },
};
